// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getChannelStats = `-- name: GetChannelStats :many
SELECT channel_id, date, views, shares, new_members, left_members FROM channel_stats
WHERE channel_id = $1
  AND date >= $2
  AND date <= $3
ORDER BY date ASC
`

type GetChannelStatsParams struct {
	ChannelID uuid.UUID `json:"channel_id"`
	Date      time.Time `json:"date"`
	Date_2    time.Time `json:"date_2"`
}

func (q *Queries) GetChannelStats(ctx context.Context, arg GetChannelStatsParams) ([]ChannelStat, error) {
	rows, err := q.db.QueryContext(ctx, getChannelStats, arg.ChannelID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelStat
	for rows.Next() {
		var i ChannelStat
		if err := rows.Scan(
			&i.ChannelID,
			&i.Date,
			&i.Views,
			&i.Shares,
			&i.NewMembers,
			&i.LeftMembers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelStatsSummary = `-- name: GetChannelStatsSummary :one
SELECT
    SUM(views)        AS total_views,
    SUM(shares)       AS total_shares,
    SUM(new_members)  AS total_new_members,
    SUM(left_members) AS total_left_members
FROM channel_stats
WHERE channel_id = $1
  AND date >= $2
  AND date <= $3
`

type GetChannelStatsSummaryParams struct {
	ChannelID uuid.UUID `json:"channel_id"`
	Date      time.Time `json:"date"`
	Date_2    time.Time `json:"date_2"`
}

type GetChannelStatsSummaryRow struct {
	TotalViews       int64 `json:"total_views"`
	TotalShares      int64 `json:"total_shares"`
	TotalNewMembers  int64 `json:"total_new_members"`
	TotalLeftMembers int64 `json:"total_left_members"`
}

func (q *Queries) GetChannelStatsSummary(ctx context.Context, arg GetChannelStatsSummaryParams) (GetChannelStatsSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getChannelStatsSummary, arg.ChannelID, arg.Date, arg.Date_2)
	var i GetChannelStatsSummaryRow
	err := row.Scan(
		&i.TotalViews,
		&i.TotalShares,
		&i.TotalNewMembers,
		&i.TotalLeftMembers,
	)
	return i, err
}

const recordChannelStat = `-- name: RecordChannelStat :exec
INSERT INTO channel_stats (channel_id, date, views, shares, new_members, left_members)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (channel_id, date) DO UPDATE SET
    views        = channel_stats.views + EXCLUDED.views,
    shares       = channel_stats.shares + EXCLUDED.shares,
    new_members  = channel_stats.new_members + EXCLUDED.new_members,
    left_members = channel_stats.left_members + EXCLUDED.left_members
`

type RecordChannelStatParams struct {
	ChannelID   uuid.UUID     `json:"channel_id"`
	Date        time.Time     `json:"date"`
	Views       sql.NullInt32 `json:"views"`
	Shares      sql.NullInt32 `json:"shares"`
	NewMembers  sql.NullInt32 `json:"new_members"`
	LeftMembers sql.NullInt32 `json:"left_members"`
}

func (q *Queries) RecordChannelStat(ctx context.Context, arg RecordChannelStatParams) error {
	_, err := q.db.ExecContext(ctx, recordChannelStat,
		arg.ChannelID,
		arg.Date,
		arg.Views,
		arg.Shares,
		arg.NewMembers,
		arg.LeftMembers,
	)
	return err
}
