// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: animated_emoji.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const getAnimatedEmoji = `-- name: GetAnimatedEmoji :one
SELECT id, emoji, object_key, bucket, width, height, created_at FROM animated_emoji WHERE emoji = $1
`

func (q *Queries) GetAnimatedEmoji(ctx context.Context, emoji string) (AnimatedEmoji, error) {
	row := q.db.QueryRowContext(ctx, getAnimatedEmoji, emoji)
	var i AnimatedEmoji
	err := row.Scan(
		&i.ID,
		&i.Emoji,
		&i.ObjectKey,
		&i.Bucket,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}

const getAnimatedEmojiBatch = `-- name: GetAnimatedEmojiBatch :many
SELECT id, emoji, object_key, bucket, width, height, created_at FROM animated_emoji WHERE emoji = ANY($1::text[])
`

// Получить несколько эмодзи за раз (для предзагрузки)
func (q *Queries) GetAnimatedEmojiBatch(ctx context.Context, dollar_1 []string) ([]AnimatedEmoji, error) {
	rows, err := q.db.QueryContext(ctx, getAnimatedEmojiBatch, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnimatedEmoji
	for rows.Next() {
		var i AnimatedEmoji
		if err := rows.Scan(
			&i.ID,
			&i.Emoji,
			&i.ObjectKey,
			&i.Bucket,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnimatedEmoji = `-- name: ListAnimatedEmoji :many
SELECT emoji, object_key FROM animated_emoji ORDER BY id
`

type ListAnimatedEmojiRow struct {
	Emoji     string `json:"emoji"`
	ObjectKey string `json:"object_key"`
}

func (q *Queries) ListAnimatedEmoji(ctx context.Context) ([]ListAnimatedEmojiRow, error) {
	rows, err := q.db.QueryContext(ctx, listAnimatedEmoji)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnimatedEmojiRow
	for rows.Next() {
		var i ListAnimatedEmojiRow
		if err := rows.Scan(&i.Emoji, &i.ObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAnimatedEmoji = `-- name: UpsertAnimatedEmoji :exec
INSERT INTO animated_emoji (emoji, object_key, bucket)
VALUES ($1, $2, $3)
ON CONFLICT (emoji) DO UPDATE
    SET object_key = EXCLUDED.object_key,
        bucket     = EXCLUDED.bucket
`

type UpsertAnimatedEmojiParams struct {
	Emoji     string `json:"emoji"`
	ObjectKey string `json:"object_key"`
	Bucket    string `json:"bucket"`
}

func (q *Queries) UpsertAnimatedEmoji(ctx context.Context, arg UpsertAnimatedEmojiParams) error {
	_, err := q.db.ExecContext(ctx, upsertAnimatedEmoji, arg.Emoji, arg.ObjectKey, arg.Bucket)
	return err
}
