// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocks.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const blockUser = `-- name: BlockUser :exec
INSERT INTO user_blocks (blocker_id, blocked_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type BlockUserParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.ExecContext(ctx, blockUser, arg.BlockerID, arg.BlockedID)
	return err
}

const getBlockedUsers = `-- name: GetBlockedUsers :many
SELECT u.id, u.username, u.avatar_url
FROM user_blocks b
JOIN users u ON u.id = b.blocked_id
WHERE b.blocker_id = $1
ORDER BY b.created_at DESC
`

type GetBlockedUsersRow struct {
	ID        uuid.UUID      `json:"id"`
	Username  string         `json:"username"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) GetBlockedUsers(ctx context.Context, blockerID uuid.UUID) ([]GetBlockedUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getBlockedUsers, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlockedUsersRow
	for rows.Next() {
		var i GetBlockedUsersRow
		if err := rows.Scan(&i.ID, &i.Username, &i.AvatarUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isBlocked = `-- name: IsBlocked :one
SELECT EXISTS (
    SELECT 1 FROM user_blocks
    WHERE blocker_id = $1 AND blocked_id = $2
) AS blocked
`

type IsBlockedParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) IsBlocked(ctx context.Context, arg IsBlockedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isBlocked, arg.BlockerID, arg.BlockedID)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const unblockUser = `-- name: UnblockUser :exec
DELETE FROM user_blocks
WHERE blocker_id = $1 AND blocked_id = $2
`

type UnblockUserParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) error {
	_, err := q.db.ExecContext(ctx, unblockUser, arg.BlockerID, arg.BlockedID)
	return err
}
