// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bots.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createBot = `-- name: CreateBot :one
INSERT INTO bots (owner_id, user_id, token, username, name, description, is_ai_enabled)
VALUES ($1, $1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, token, username, name, description, avatar_url, is_active, is_ai_enabled, webhook_url, webhook_secret, created_at
`

type CreateBotParams struct {
	OwnerID     uuid.UUID `json:"owner_id"`
	Token       string    `json:"token"`
	Username    string    `json:"username"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsAiEnabled bool      `json:"is_ai_enabled"`
}

func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) (Bot, error) {
	row := q.db.QueryRowContext(ctx, createBot,
		arg.OwnerID,
		arg.Token,
		arg.Username,
		arg.Name,
		arg.Description,
		arg.IsAiEnabled,
	)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Token,
		&i.Username,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.IsActive,
		&i.IsAiEnabled,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.CreatedAt,
	)
	return i, err
}

const createBotCommand = `-- name: CreateBotCommand :exec
INSERT INTO bot_commands (bot_id, command, description)
VALUES ($1, $2, $3)
ON CONFLICT (bot_id, command) DO UPDATE
SET description = EXCLUDED.description
`

type CreateBotCommandParams struct {
	BotID       uuid.UUID `json:"bot_id"`
	Command     string    `json:"command"`
	Description string    `json:"description"`
}

func (q *Queries) CreateBotCommand(ctx context.Context, arg CreateBotCommandParams) error {
	_, err := q.db.ExecContext(ctx, createBotCommand, arg.BotID, arg.Command, arg.Description)
	return err
}

const deactivateBot = `-- name: DeactivateBot :exec
UPDATE bots
SET is_active = false
WHERE id = $1 AND owner_id = $2
`

type DeactivateBotParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) DeactivateBot(ctx context.Context, arg DeactivateBotParams) error {
	_, err := q.db.ExecContext(ctx, deactivateBot, arg.ID, arg.OwnerID)
	return err
}

const deleteBotCommand = `-- name: DeleteBotCommand :exec
DELETE FROM bot_commands
WHERE bot_id = $1 AND command = $2
`

type DeleteBotCommandParams struct {
	BotID   uuid.UUID `json:"bot_id"`
	Command string    `json:"command"`
}

func (q *Queries) DeleteBotCommand(ctx context.Context, arg DeleteBotCommandParams) error {
	_, err := q.db.ExecContext(ctx, deleteBotCommand, arg.BotID, arg.Command)
	return err
}

const getBotByID = `-- name: GetBotByID :one
SELECT id, owner_id, token, username, name, description, avatar_url, is_active, is_ai_enabled, webhook_url, webhook_secret, created_at FROM bots
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBotByID(ctx context.Context, id uuid.UUID) (Bot, error) {
	row := q.db.QueryRowContext(ctx, getBotByID, id)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Token,
		&i.Username,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.IsActive,
		&i.IsAiEnabled,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.CreatedAt,
	)
	return i, err
}

const getBotByToken = `-- name: GetBotByToken :one
SELECT id, owner_id, token, username, name, description, avatar_url, is_active, is_ai_enabled, webhook_url, webhook_secret, created_at FROM bots
WHERE token = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) GetBotByToken(ctx context.Context, token string) (Bot, error) {
	row := q.db.QueryRowContext(ctx, getBotByToken, token)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Token,
		&i.Username,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.IsActive,
		&i.IsAiEnabled,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.CreatedAt,
	)
	return i, err
}

const getBotCommands = `-- name: GetBotCommands :many
SELECT id, bot_id, command, description FROM bot_commands
WHERE bot_id = $1
ORDER BY command ASC
`

func (q *Queries) GetBotCommands(ctx context.Context, botID uuid.UUID) ([]BotCommand, error) {
	rows, err := q.db.QueryContext(ctx, getBotCommands, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotCommand
	for rows.Next() {
		var i BotCommand
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Command,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMyBots = `-- name: GetMyBots :many
SELECT id, owner_id, token, username, name, description, avatar_url, is_active, is_ai_enabled, webhook_url, webhook_secret, created_at FROM bots
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetMyBots(ctx context.Context, ownerID uuid.UUID) ([]Bot, error) {
	rows, err := q.db.QueryContext(ctx, getMyBots, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bot
	for rows.Next() {
		var i Bot
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Token,
			&i.Username,
			&i.Name,
			&i.Description,
			&i.AvatarUrl,
			&i.IsActive,
			&i.IsAiEnabled,
			&i.WebhookUrl,
			&i.WebhookSecret,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnprocessedUpdates = `-- name: GetUnprocessedUpdates :many
SELECT id, bot_id, update_id, type, payload, processed, created_at FROM bot_updates
WHERE bot_id = $1 AND processed = false
ORDER BY update_id ASC
LIMIT 100
`

func (q *Queries) GetUnprocessedUpdates(ctx context.Context, botID uuid.UUID) ([]BotUpdate, error) {
	rows, err := q.db.QueryContext(ctx, getUnprocessedUpdates, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotUpdate
	for rows.Next() {
		var i BotUpdate
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.UpdateID,
			&i.Type,
			&i.Payload,
			&i.Processed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUpdateProcessed = `-- name: MarkUpdateProcessed :exec
UPDATE bot_updates
SET processed = true
WHERE id = $1
`

func (q *Queries) MarkUpdateProcessed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markUpdateProcessed, id)
	return err
}

const saveBotUpdate = `-- name: SaveBotUpdate :exec
INSERT INTO bot_updates (bot_id, update_id, type, payload)
VALUES ($1, $2, $3, $4)
ON CONFLICT (bot_id, update_id) DO NOTHING
`

type SaveBotUpdateParams struct {
	BotID    uuid.UUID       `json:"bot_id"`
	UpdateID int64           `json:"update_id"`
	Type     string          `json:"type"`
	Payload  json.RawMessage `json:"payload"`
}

func (q *Queries) SaveBotUpdate(ctx context.Context, arg SaveBotUpdateParams) error {
	_, err := q.db.ExecContext(ctx, saveBotUpdate,
		arg.BotID,
		arg.UpdateID,
		arg.Type,
		arg.Payload,
	)
	return err
}

const updateBotWebhook = `-- name: UpdateBotWebhook :exec
UPDATE bots
SET webhook_url = $2, webhook_secret = $3
WHERE id = $1
`

type UpdateBotWebhookParams struct {
	ID            uuid.UUID `json:"id"`
	WebhookUrl    string    `json:"webhook_url"`
	WebhookSecret string    `json:"webhook_secret"`
}

func (q *Queries) UpdateBotWebhook(ctx context.Context, arg UpdateBotWebhookParams) error {
	_, err := q.db.ExecContext(ctx, updateBotWebhook, arg.ID, arg.WebhookUrl, arg.WebhookSecret)
	return err
}
