// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addChatMember = `-- name: AddChatMember :exec
INSERT INTO chat_members (chat_id,user_id,role)VALUES ($1,$2,$3)
`

type AddChatMemberParams struct {
	ChatID uuid.UUID      `json:"chat_id"`
	UserID uuid.UUID      `json:"user_id"`
	Role   sql.NullString `json:"role"`
}

func (q *Queries) AddChatMember(ctx context.Context, arg AddChatMemberParams) error {
	_, err := q.db.ExecContext(ctx, addChatMember, arg.ChatID, arg.UserID, arg.Role)
	return err
}

const createChat = `-- name: CreateChat :one
INSERT INTO chats(type,name,owner_id,is_public)
VALUES ($1,$2,$3,$4) RETURNING id, type, name, username, avatar_url, description, owner_id, is_public, is_deleted, slow_mode, member_count, invite_link, created_at, updated_at, metadata
`

type CreateChatParams struct {
	Type     string         `json:"type"`
	Name     sql.NullString `json:"name"`
	OwnerID  uuid.NullUUID  `json:"owner_id"`
	IsPublic sql.NullBool   `json:"is_public"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, createChat,
		arg.Type,
		arg.Name,
		arg.OwnerID,
		arg.IsPublic,
	)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Username,
		&i.AvatarUrl,
		&i.Description,
		&i.OwnerID,
		&i.IsPublic,
		&i.IsDeleted,
		&i.SlowMode,
		&i.MemberCount,
		&i.InviteLink,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getChatByID = `-- name: GetChatByID :one
SELECT id, type, name, username, avatar_url, description, owner_id, is_public, is_deleted, slow_mode, member_count, invite_link, created_at, updated_at, metadata FROM chats WHERE id=$1 AND is_deleted=FALSE
`

func (q *Queries) GetChatByID(ctx context.Context, id uuid.UUID) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Username,
		&i.AvatarUrl,
		&i.Description,
		&i.OwnerID,
		&i.IsPublic,
		&i.IsDeleted,
		&i.SlowMode,
		&i.MemberCount,
		&i.InviteLink,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getChatMembers = `-- name: GetChatMembers :many
SELECT chat_id, user_id, role, muted_until, is_banned, last_read_at, joined_at, metadata FROM chat_members WHERE chat_id =$1 AND is_banned =FALSE
`

func (q *Queries) GetChatMembers(ctx context.Context, chatID uuid.UUID) ([]ChatMember, error) {
	rows, err := q.db.QueryContext(ctx, getChatMembers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMember
	for rows.Next() {
		var i ChatMember
		if err := rows.Scan(
			&i.ChatID,
			&i.UserID,
			&i.Role,
			&i.MutedUntil,
			&i.IsBanned,
			&i.LastReadAt,
			&i.JoinedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserChats = `-- name: GetUserChats :many
SELECT c.id, c.type, c.name, c.username, c.avatar_url, c.description, c.owner_id, c.is_public, c.is_deleted, c.slow_mode, c.member_count, c.invite_link, c.created_at, c.updated_at, c.metadata FROM chats c JOIN chat_members cm ON c.id = cm.chat_id
WHERE cm.user_id =$1 AND c.is_deleted =FALSE ORDER BY c.updated_at DESC
`

func (q *Queries) GetUserChats(ctx context.Context, userID uuid.UUID) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, getUserChats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Username,
			&i.AvatarUrl,
			&i.Description,
			&i.OwnerID,
			&i.IsPublic,
			&i.IsDeleted,
			&i.SlowMode,
			&i.MemberCount,
			&i.InviteLink,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeChatMember = `-- name: RemoveChatMember :exec
DELETE FROM chat_members WHERE chat_id = $1 AND user_id =$2
`

type RemoveChatMemberParams struct {
	ChatID uuid.UUID `json:"chat_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveChatMember(ctx context.Context, arg RemoveChatMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeChatMember, arg.ChatID, arg.UserID)
	return err
}

const updateChatMemberRole = `-- name: UpdateChatMemberRole :exec
UPDATE chat_members SET role = $3 WHERE chat_id =$1 AND user_id =$2
`

type UpdateChatMemberRoleParams struct {
	ChatID uuid.UUID      `json:"chat_id"`
	UserID uuid.UUID      `json:"user_id"`
	Role   sql.NullString `json:"role"`
}

func (q *Queries) UpdateChatMemberRole(ctx context.Context, arg UpdateChatMemberRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateChatMemberRole, arg.ChatID, arg.UserID, arg.Role)
	return err
}
