// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices(user_id,push_token,platform,device_name)
VALUES($1,$2,$3,$4)RETURNING id, user_id, push_token, platform, device_name, last_active, is_active, created_at, metadata
`

type CreateDeviceParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	PushToken  sql.NullString `json:"push_token"`
	Platform   string         `json:"platform"`
	DeviceName sql.NullString `json:"device_name"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice,
		arg.UserID,
		arg.PushToken,
		arg.Platform,
		arg.DeviceName,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PushToken,
		&i.Platform,
		&i.DeviceName,
		&i.LastActive,
		&i.IsActive,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const deactivateDevice = `-- name: DeactivateDevice :exec
UPDATE devices SET is_active = FALSE WHERE id = $1
`

func (q *Queries) DeactivateDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateDevice, id)
	return err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = $1
`

func (q *Queries) DeleteDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, id)
	return err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, user_id, push_token, platform, device_name, last_active, is_active, created_at, metadata FROM devices WHERE id =$1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PushToken,
		&i.Platform,
		&i.DeviceName,
		&i.LastActive,
		&i.IsActive,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const getUserDevices = `-- name: GetUserDevices :one
SELECT id, user_id, push_token, platform, device_name, last_active, is_active, created_at, metadata FROM devices WHERE user_id = $1 AND is_active= TRUE
`

func (q *Queries) GetUserDevices(ctx context.Context, userID uuid.UUID) (Device, error) {
	row := q.db.QueryRowContext(ctx, getUserDevices, userID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PushToken,
		&i.Platform,
		&i.DeviceName,
		&i.LastActive,
		&i.IsActive,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const updateDevicePushToken = `-- name: UpdateDevicePushToken :exec
UPDATE devices SET push_token=$2, last_active = NOW() WHERE id =$1
`

type UpdateDevicePushTokenParams struct {
	ID        uuid.UUID      `json:"id"`
	PushToken sql.NullString `json:"push_token"`
}

func (q *Queries) UpdateDevicePushToken(ctx context.Context, arg UpdateDevicePushTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateDevicePushToken, arg.ID, arg.PushToken)
	return err
}
