// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: emoji.sql

package db

import (
	"context"
	"database/sql"
)

const addEmojiKeyword = `-- name: AddEmojiKeyword :exec
INSERT INTO emoji_keywords (keyword, emoji, lang, weight)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AddEmojiKeywordParams struct {
	Keyword string         `json:"keyword"`
	Emoji   string         `json:"emoji"`
	Lang    sql.NullString `json:"lang"`
	Weight  sql.NullInt32  `json:"weight"`
}

func (q *Queries) AddEmojiKeyword(ctx context.Context, arg AddEmojiKeywordParams) error {
	_, err := q.db.ExecContext(ctx, addEmojiKeyword,
		arg.Keyword,
		arg.Emoji,
		arg.Lang,
		arg.Weight,
	)
	return err
}

const getEmojiByKeyword = `-- name: GetEmojiByKeyword :many
SELECT DISTINCT ON (emoji) emoji, MAX(weight) as weight
FROM emoji_keywords
WHERE keyword ILIKE '%' || $1 || '%'
GROUP BY emoji
ORDER BY emoji, weight DESC
LIMIT 8
`

type GetEmojiByKeywordRow struct {
	Emoji  string      `json:"emoji"`
	Weight interface{} `json:"weight"`
}

// Ищет эмодзи по тексту (для inline suggestions при вводе обычного текста)
// Возвращает уникальные эмодзи, отсортированные по весу
func (q *Queries) GetEmojiByKeyword(ctx context.Context, dollar_1 sql.NullString) ([]GetEmojiByKeywordRow, error) {
	rows, err := q.db.QueryContext(ctx, getEmojiByKeyword, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEmojiByKeywordRow
	for rows.Next() {
		var i GetEmojiByKeywordRow
		if err := rows.Scan(&i.Emoji, &i.Weight); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
