// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: keys.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countAvailableOneTimePreKeys = `-- name: CountAvailableOneTimePreKeys :one
SELECT COUNT(*) FROM one_time_prekeys
WHERE user_id = $1 AND device_id = $2 AND is_used = FALSE
`

type CountAvailableOneTimePreKeysParams struct {
	UserID   uuid.UUID     `json:"user_id"`
	DeviceID uuid.NullUUID `json:"device_id"`
}

func (q *Queries) CountAvailableOneTimePreKeys(ctx context.Context, arg CountAvailableOneTimePreKeysParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAvailableOneTimePreKeys, arg.UserID, arg.DeviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldSignedPreKeys = `-- name: DeleteOldSignedPreKeys :exec
DELETE FROM signed_prekeys
WHERE user_id = $1 AND device_id = $2
  AND key_id != $3
`

type DeleteOldSignedPreKeysParams struct {
	UserID   uuid.UUID     `json:"user_id"`
	DeviceID uuid.NullUUID `json:"device_id"`
	KeyID    int32         `json:"key_id"`
}

func (q *Queries) DeleteOldSignedPreKeys(ctx context.Context, arg DeleteOldSignedPreKeysParams) error {
	_, err := q.db.ExecContext(ctx, deleteOldSignedPreKeys, arg.UserID, arg.DeviceID, arg.KeyID)
	return err
}

const getAndUseOneTimePreKey = `-- name: GetAndUseOneTimePreKey :one
UPDATE one_time_prekeys
SET is_used = TRUE, used_at = NOW()
WHERE id = (
    SELECT otpk.id FROM one_time_prekeys otpk
    WHERE otpk.user_id = $1
      AND otpk.device_id = $2
      AND otpk.is_used = FALSE
    ORDER BY otpk.created_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, user_id, device_id, key_id, public_key, is_used, used_at, created_at
`

type GetAndUseOneTimePreKeyParams struct {
	UserID   uuid.UUID     `json:"user_id"`
	DeviceID uuid.NullUUID `json:"device_id"`
}

func (q *Queries) GetAndUseOneTimePreKey(ctx context.Context, arg GetAndUseOneTimePreKeyParams) (OneTimePrekey, error) {
	row := q.db.QueryRowContext(ctx, getAndUseOneTimePreKey, arg.UserID, arg.DeviceID)
	var i OneTimePrekey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.KeyID,
		&i.PublicKey,
		&i.IsUsed,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentityKey = `-- name: GetIdentityKey :one
SELECT id, user_id, device_id, public_key, registration_id, created_at FROM identity_keys
WHERE user_id = $1 AND device_id = $2
`

type GetIdentityKeyParams struct {
	UserID   uuid.UUID     `json:"user_id"`
	DeviceID uuid.NullUUID `json:"device_id"`
}

func (q *Queries) GetIdentityKey(ctx context.Context, arg GetIdentityKeyParams) (IdentityKey, error) {
	row := q.db.QueryRowContext(ctx, getIdentityKey, arg.UserID, arg.DeviceID)
	var i IdentityKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.PublicKey,
		&i.RegistrationID,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentityKeysByUser = `-- name: GetIdentityKeysByUser :many
SELECT id, user_id, device_id, public_key, registration_id, created_at FROM identity_keys
WHERE user_id = $1
`

func (q *Queries) GetIdentityKeysByUser(ctx context.Context, userID uuid.UUID) ([]IdentityKey, error) {
	rows, err := q.db.QueryContext(ctx, getIdentityKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityKey
	for rows.Next() {
		var i IdentityKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.PublicKey,
			&i.RegistrationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKeyBundle = `-- name: GetKeyBundle :one
SELECT user_id, device_id, bundle, updated_at FROM key_bundles
WHERE user_id = $1 AND device_id = $2
`

type GetKeyBundleParams struct {
	UserID   uuid.UUID `json:"user_id"`
	DeviceID uuid.UUID `json:"device_id"`
}

func (q *Queries) GetKeyBundle(ctx context.Context, arg GetKeyBundleParams) (KeyBundle, error) {
	row := q.db.QueryRowContext(ctx, getKeyBundle, arg.UserID, arg.DeviceID)
	var i KeyBundle
	err := row.Scan(
		&i.UserID,
		&i.DeviceID,
		&i.Bundle,
		&i.UpdatedAt,
	)
	return i, err
}

const getKeyBundlesByUser = `-- name: GetKeyBundlesByUser :many
SELECT user_id, device_id, bundle, updated_at FROM key_bundles
WHERE user_id = $1
`

func (q *Queries) GetKeyBundlesByUser(ctx context.Context, userID uuid.UUID) ([]KeyBundle, error) {
	rows, err := q.db.QueryContext(ctx, getKeyBundlesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KeyBundle
	for rows.Next() {
		var i KeyBundle
		if err := rows.Scan(
			&i.UserID,
			&i.DeviceID,
			&i.Bundle,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSignedPreKey = `-- name: GetSignedPreKey :one
SELECT id, user_id, device_id, key_id, public_key, signature, created_at FROM signed_prekeys
WHERE user_id = $1 AND device_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetSignedPreKeyParams struct {
	UserID   uuid.UUID     `json:"user_id"`
	DeviceID uuid.NullUUID `json:"device_id"`
}

func (q *Queries) GetSignedPreKey(ctx context.Context, arg GetSignedPreKeyParams) (SignedPrekey, error) {
	row := q.db.QueryRowContext(ctx, getSignedPreKey, arg.UserID, arg.DeviceID)
	var i SignedPrekey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.KeyID,
		&i.PublicKey,
		&i.Signature,
		&i.CreatedAt,
	)
	return i, err
}

const saveIdentityKey = `-- name: SaveIdentityKey :one
INSERT INTO identity_keys (user_id, device_id, public_key, registration_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, device_id) DO UPDATE
    SET public_key = EXCLUDED.public_key,
        registration_id = EXCLUDED.registration_id
RETURNING id, user_id, device_id, public_key, registration_id, created_at
`

type SaveIdentityKeyParams struct {
	UserID         uuid.UUID     `json:"user_id"`
	DeviceID       uuid.NullUUID `json:"device_id"`
	PublicKey      string        `json:"public_key"`
	RegistrationID int32         `json:"registration_id"`
}

func (q *Queries) SaveIdentityKey(ctx context.Context, arg SaveIdentityKeyParams) (IdentityKey, error) {
	row := q.db.QueryRowContext(ctx, saveIdentityKey,
		arg.UserID,
		arg.DeviceID,
		arg.PublicKey,
		arg.RegistrationID,
	)
	var i IdentityKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.PublicKey,
		&i.RegistrationID,
		&i.CreatedAt,
	)
	return i, err
}

const saveKeyBundle = `-- name: SaveKeyBundle :one

INSERT INTO key_bundles (user_id, device_id, bundle, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id, device_id) DO UPDATE
    SET bundle     = EXCLUDED.bundle,
        updated_at = NOW()
RETURNING user_id, device_id, bundle, updated_at
`

type SaveKeyBundleParams struct {
	UserID   uuid.UUID       `json:"user_id"`
	DeviceID uuid.UUID       `json:"device_id"`
	Bundle   json.RawMessage `json:"bundle"`
}

// ============================================
// KEY BUNDLE
// ============================================
func (q *Queries) SaveKeyBundle(ctx context.Context, arg SaveKeyBundleParams) (KeyBundle, error) {
	row := q.db.QueryRowContext(ctx, saveKeyBundle, arg.UserID, arg.DeviceID, arg.Bundle)
	var i KeyBundle
	err := row.Scan(
		&i.UserID,
		&i.DeviceID,
		&i.Bundle,
		&i.UpdatedAt,
	)
	return i, err
}

const saveOneTimePreKey = `-- name: SaveOneTimePreKey :exec

INSERT INTO one_time_prekeys (user_id, device_id, key_id, public_key)
VALUES ($1, $2, $3, $4)
`

type SaveOneTimePreKeyParams struct {
	UserID    uuid.UUID     `json:"user_id"`
	DeviceID  uuid.NullUUID `json:"device_id"`
	KeyID     int32         `json:"key_id"`
	PublicKey string        `json:"public_key"`
}

// ============================================
// ONE-TIME PREKEYS
// ============================================
func (q *Queries) SaveOneTimePreKey(ctx context.Context, arg SaveOneTimePreKeyParams) error {
	_, err := q.db.ExecContext(ctx, saveOneTimePreKey,
		arg.UserID,
		arg.DeviceID,
		arg.KeyID,
		arg.PublicKey,
	)
	return err
}

const saveSignedPreKey = `-- name: SaveSignedPreKey :one

INSERT INTO signed_prekeys (user_id, device_id, key_id, public_key, signature)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, device_id, key_id) DO UPDATE
    SET public_key = EXCLUDED.public_key,
        signature  = EXCLUDED.signature
RETURNING id, user_id, device_id, key_id, public_key, signature, created_at
`

type SaveSignedPreKeyParams struct {
	UserID    uuid.UUID     `json:"user_id"`
	DeviceID  uuid.NullUUID `json:"device_id"`
	KeyID     int32         `json:"key_id"`
	PublicKey string        `json:"public_key"`
	Signature string        `json:"signature"`
}

// ============================================
// SIGNED PREKEYS
// ============================================
func (q *Queries) SaveSignedPreKey(ctx context.Context, arg SaveSignedPreKeyParams) (SignedPrekey, error) {
	row := q.db.QueryRowContext(ctx, saveSignedPreKey,
		arg.UserID,
		arg.DeviceID,
		arg.KeyID,
		arg.PublicKey,
		arg.Signature,
	)
	var i SignedPrekey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.KeyID,
		&i.PublicKey,
		&i.Signature,
		&i.CreatedAt,
	)
	return i, err
}
