// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
    uploader_id,
    type,
    status,
    bucket,
    object_key,
    original_name,
    mime_type
) VALUES (
    $1, $2, 'pending', $3, $4, $5, $6
)
RETURNING id, uploader_id, type, status, bucket, object_key, original_name, mime_type, size_bytes, width, height, duration_sec, thumb_key, waveform, blur_hash, created_at, expires_at
`

type CreateMediaParams struct {
	UploaderID   uuid.UUID      `json:"uploader_id"`
	Type         MediaType      `json:"type"`
	Bucket       string         `json:"bucket"`
	ObjectKey    string         `json:"object_key"`
	OriginalName sql.NullString `json:"original_name"`
	MimeType     string         `json:"mime_type"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.UploaderID,
		arg.Type,
		arg.Bucket,
		arg.ObjectKey,
		arg.OriginalName,
		arg.MimeType,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.Type,
		&i.Status,
		&i.Bucket,
		&i.ObjectKey,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.DurationSec,
		&i.ThumbKey,
		&i.Waveform,
		&i.BlurHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media
WHERE id = $1
`

func (q *Queries) DeleteMedia(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMedia, id)
	return err
}

const getMedia = `-- name: GetMedia :one
SELECT id, uploader_id, type, status, bucket, object_key, original_name, mime_type, size_bytes, width, height, duration_sec, thumb_key, waveform, blur_hash, created_at, expires_at FROM media
WHERE id = $1
`

func (q *Queries) GetMedia(ctx context.Context, id uuid.UUID) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.Type,
		&i.Status,
		&i.Bucket,
		&i.ObjectKey,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.DurationSec,
		&i.ThumbKey,
		&i.Waveform,
		&i.BlurHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPendingExpiredMedia = `-- name: GetPendingExpiredMedia :many
SELECT id, uploader_id, type, status, bucket, object_key, original_name, mime_type, size_bytes, width, height, duration_sec, thumb_key, waveform, blur_hash, created_at, expires_at FROM media
WHERE status = 'pending'
AND created_at < NOW() - INTERVAL '24 hours'
`

func (q *Queries) GetPendingExpiredMedia(ctx context.Context) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, getPendingExpiredMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.UploaderID,
			&i.Type,
			&i.Status,
			&i.Bucket,
			&i.ObjectKey,
			&i.OriginalName,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.DurationSec,
			&i.ThumbKey,
			&i.Waveform,
			&i.BlurHash,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingMedia = `-- name: GetPendingMedia :many
SELECT id, uploader_id, type, status, bucket, object_key, original_name, mime_type, size_bytes, width, height, duration_sec, thumb_key, waveform, blur_hash, created_at, expires_at FROM media WHERE status = 'uploaded' LIMIT 10
`

func (q *Queries) GetPendingMedia(ctx context.Context) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, getPendingMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.UploaderID,
			&i.Type,
			&i.Status,
			&i.Bucket,
			&i.ObjectKey,
			&i.OriginalName,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.DurationSec,
			&i.ThumbKey,
			&i.Waveform,
			&i.BlurHash,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMediaFailed = `-- name: SetMediaFailed :exec
UPDATE media SET status = 'failed' WHERE id = $1
`

func (q *Queries) SetMediaFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setMediaFailed, id)
	return err
}

const setMediaProcessed = `-- name: SetMediaProcessed :exec
UPDATE media SET status = 'processed' WHERE id = $1
`

func (q *Queries) SetMediaProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setMediaProcessed, id)
	return err
}

const setMediaProcessedWithThumb = `-- name: SetMediaProcessedWithThumb :exec
UPDATE media SET status = 'processed', thumb_key = $2 WHERE id = $1
`

type SetMediaProcessedWithThumbParams struct {
	ID       uuid.UUID      `json:"id"`
	ThumbKey sql.NullString `json:"thumb_key"`
}

func (q *Queries) SetMediaProcessedWithThumb(ctx context.Context, arg SetMediaProcessedWithThumbParams) error {
	_, err := q.db.ExecContext(ctx, setMediaProcessedWithThumb, arg.ID, arg.ThumbKey)
	return err
}

const setMediaProcessedWithWaveform = `-- name: SetMediaProcessedWithWaveform :exec
UPDATE media
SET status = 'processed', waveform = $2
WHERE id = $1
`

type SetMediaProcessedWithWaveformParams struct {
	ID       uuid.UUID             `json:"id"`
	Waveform pqtype.NullRawMessage `json:"waveform"`
}

func (q *Queries) SetMediaProcessedWithWaveform(ctx context.Context, arg SetMediaProcessedWithWaveformParams) error {
	_, err := q.db.ExecContext(ctx, setMediaProcessedWithWaveform, arg.ID, arg.Waveform)
	return err
}

const updateMediaStatus = `-- name: UpdateMediaStatus :one
UPDATE media
SET status = $2
WHERE id = $1
RETURNING id, uploader_id, type, status, bucket, object_key, original_name, mime_type, size_bytes, width, height, duration_sec, thumb_key, waveform, blur_hash, created_at, expires_at
`

type UpdateMediaStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status MediaStatus `json:"status"`
}

func (q *Queries) UpdateMediaStatus(ctx context.Context, arg UpdateMediaStatusParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, updateMediaStatus, arg.ID, arg.Status)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.Type,
		&i.Status,
		&i.Bucket,
		&i.ObjectKey,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.DurationSec,
		&i.ThumbKey,
		&i.Waveform,
		&i.BlurHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateMediaUploaded = `-- name: UpdateMediaUploaded :one
UPDATE media
SET
    status = 'uploaded',
    size_bytes = $2,
    width = $3,
    height = $4,
    duration_sec = $5
WHERE id = $1
RETURNING id, uploader_id, type, status, bucket, object_key, original_name, mime_type, size_bytes, width, height, duration_sec, thumb_key, waveform, blur_hash, created_at, expires_at
`

type UpdateMediaUploadedParams struct {
	ID          uuid.UUID       `json:"id"`
	SizeBytes   sql.NullInt64   `json:"size_bytes"`
	Width       sql.NullInt32   `json:"width"`
	Height      sql.NullInt32   `json:"height"`
	DurationSec sql.NullFloat64 `json:"duration_sec"`
}

func (q *Queries) UpdateMediaUploaded(ctx context.Context, arg UpdateMediaUploadedParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, updateMediaUploaded,
		arg.ID,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.DurationSec,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.Type,
		&i.Status,
		&i.Bucket,
		&i.ObjectKey,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.DurationSec,
		&i.ThumbKey,
		&i.Waveform,
		&i.BlurHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
