// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages(chat_id,sender_id,type,content,reply_to_id)
VALUES ($1,$2,$3,$4,$5) RETURNING id, chat_id, sender_id, reply_to_id, thread_id, forwarded_from_id, type, content, is_encrypted, is_edited, is_deleted, is_pinned, scheduled_at, expires_at, views_count, created_at, updated_at, metadata
`

type CreateMessageParams struct {
	ChatID    uuid.UUID      `json:"chat_id"`
	SenderID  uuid.UUID      `json:"sender_id"`
	Type      sql.NullString `json:"type"`
	Content   sql.NullString `json:"content"`
	ReplyToID uuid.NullUUID  `json:"reply_to_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ChatID,
		arg.SenderID,
		arg.Type,
		arg.Content,
		arg.ReplyToID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.ReplyToID,
		&i.ThreadID,
		&i.ForwardedFromID,
		&i.Type,
		&i.Content,
		&i.IsEncrypted,
		&i.IsEdited,
		&i.IsDeleted,
		&i.IsPinned,
		&i.ScheduledAt,
		&i.ExpiresAt,
		&i.ViewsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const createMessageStatus = `-- name: CreateMessageStatus :exec
INSERT INTO message_status (message_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING
`

type CreateMessageStatusParams struct {
	MessageID uuid.UUID `json:"message_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateMessageStatus(ctx context.Context, arg CreateMessageStatusParams) error {
	_, err := q.db.ExecContext(ctx, createMessageStatus, arg.MessageID, arg.UserID)
	return err
}

const deleteMessageForAll = `-- name: DeleteMessageForAll :exec
UPDATE messages SET is_deleted =TRUE WHERE id =$1
`

func (q *Queries) DeleteMessageForAll(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMessageForAll, id)
	return err
}

const editMessage = `-- name: EditMessage :one
UPDATE messages SET content =$2,is_edited = TRUE, updated_at=NOW()
WHERE id=$1 RETURNING id, chat_id, sender_id, reply_to_id, thread_id, forwarded_from_id, type, content, is_encrypted, is_edited, is_deleted, is_pinned, scheduled_at, expires_at, views_count, created_at, updated_at, metadata
`

type EditMessageParams struct {
	ID      uuid.UUID      `json:"id"`
	Content sql.NullString `json:"content"`
}

func (q *Queries) EditMessage(ctx context.Context, arg EditMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, editMessage, arg.ID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.ReplyToID,
		&i.ThreadID,
		&i.ForwardedFromID,
		&i.Type,
		&i.Content,
		&i.IsEncrypted,
		&i.IsEdited,
		&i.IsDeleted,
		&i.IsPinned,
		&i.ScheduledAt,
		&i.ExpiresAt,
		&i.ViewsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getChatMessages = `-- name: GetChatMessages :many
SELECT id, chat_id, sender_id, reply_to_id, thread_id, forwarded_from_id, type, content, is_encrypted, is_edited, is_deleted, is_pinned, scheduled_at, expires_at, views_count, created_at, updated_at, metadata FROM messages WHERE chat_id =$1 AND is_deleted =FALSE
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type GetChatMessagesParams struct {
	ChatID uuid.UUID `json:"chat_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getChatMessages, arg.ChatID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.ReplyToID,
			&i.ThreadID,
			&i.ForwardedFromID,
			&i.Type,
			&i.Content,
			&i.IsEncrypted,
			&i.IsEdited,
			&i.IsDeleted,
			&i.IsPinned,
			&i.ScheduledAt,
			&i.ExpiresAt,
			&i.ViewsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, chat_id, sender_id, reply_to_id, thread_id, forwarded_from_id, type, content, is_encrypted, is_edited, is_deleted, is_pinned, scheduled_at, expires_at, views_count, created_at, updated_at, metadata FROM messages WHERE id=$1 AND is_deleted = FALSE
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.ReplyToID,
		&i.ThreadID,
		&i.ForwardedFromID,
		&i.Type,
		&i.Content,
		&i.IsEncrypted,
		&i.IsEdited,
		&i.IsDeleted,
		&i.IsPinned,
		&i.ScheduledAt,
		&i.ExpiresAt,
		&i.ViewsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getPinnedMessages = `-- name: GetPinnedMessages :many
SELECT id, chat_id, sender_id, reply_to_id, thread_id, forwarded_from_id, type, content, is_encrypted, is_edited, is_deleted, is_pinned, scheduled_at, expires_at, views_count, created_at, updated_at, metadata FROM messages WHERE chat_id =$1 AND is_pinned =TRUE AND is_deleted =FALSE
`

func (q *Queries) GetPinnedMessages(ctx context.Context, chatID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getPinnedMessages, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.ReplyToID,
			&i.ThreadID,
			&i.ForwardedFromID,
			&i.Type,
			&i.Content,
			&i.IsEncrypted,
			&i.IsEdited,
			&i.IsDeleted,
			&i.IsPinned,
			&i.ScheduledAt,
			&i.ExpiresAt,
			&i.ViewsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinMessage = `-- name: PinMessage :exec
UPDATE messages SET is_pinned = TRUE WHERE id =$1
`

func (q *Queries) PinMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, pinMessage, id)
	return err
}

const updateMessageDelivered = `-- name: UpdateMessageDelivered :exec
UPDATE message_status SET delivered = TRUE,delivered_at = NOW() WHERE message_id =$1 AND user_id =$2
`

type UpdateMessageDeliveredParams struct {
	MessageID uuid.UUID `json:"message_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateMessageDelivered(ctx context.Context, arg UpdateMessageDeliveredParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageDelivered, arg.MessageID, arg.UserID)
	return err
}

const updateMessageRead = `-- name: UpdateMessageRead :exec
UPDATE message_status SET read = TRUE,read_at = NOW() WHERE message_id=$1 AND user_id=$2
`

type UpdateMessageReadParams struct {
	MessageID uuid.UUID `json:"message_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateMessageRead(ctx context.Context, arg UpdateMessageReadParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageRead, arg.MessageID, arg.UserID)
	return err
}
