// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Bot struct {
	ID         uuid.UUID             `json:"id"`
	UserID     uuid.UUID             `json:"user_id"`
	OwnerID    uuid.UUID             `json:"owner_id"`
	Token      string                `json:"token"`
	WebhookUrl sql.NullString        `json:"webhook_url"`
	Commands   pqtype.NullRawMessage `json:"commands"`
	IsActive   sql.NullBool          `json:"is_active"`
	CreatedAt  sql.NullTime          `json:"created_at"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
}

type Call struct {
	ID          uuid.UUID             `json:"id"`
	ChatID      uuid.NullUUID         `json:"chat_id"`
	InitiatorID uuid.UUID             `json:"initiator_id"`
	Type        string                `json:"type"`
	Status      string                `json:"status"`
	StartedAt   sql.NullTime          `json:"started_at"`
	EndedAt     sql.NullTime          `json:"ended_at"`
	Duration    sql.NullInt32         `json:"duration"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
}

type CallParticipant struct {
	CallID     uuid.UUID    `json:"call_id"`
	UserID     uuid.UUID    `json:"user_id"`
	JoinedAt   sql.NullTime `json:"joined_at"`
	LeftAt     sql.NullTime `json:"left_at"`
	IsMuted    sql.NullBool `json:"is_muted"`
	IsVideoOff sql.NullBool `json:"is_video_off"`
}

type Chat struct {
	ID          uuid.UUID             `json:"id"`
	Type        string                `json:"type"`
	Name        sql.NullString        `json:"name"`
	Username    sql.NullString        `json:"username"`
	AvatarUrl   sql.NullString        `json:"avatar_url"`
	Description sql.NullString        `json:"description"`
	OwnerID     uuid.NullUUID         `json:"owner_id"`
	IsPublic    sql.NullBool          `json:"is_public"`
	IsDeleted   sql.NullBool          `json:"is_deleted"`
	SlowMode    sql.NullInt32         `json:"slow_mode"`
	MemberCount sql.NullInt32         `json:"member_count"`
	InviteLink  sql.NullString        `json:"invite_link"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	UpdatedAt   sql.NullTime          `json:"updated_at"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
}

type ChatFolder struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	Name      string         `json:"name"`
	Emoji     sql.NullString `json:"emoji"`
	Position  sql.NullInt32  `json:"position"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type ChatFolderItem struct {
	FolderID uuid.UUID `json:"folder_id"`
	ChatID   uuid.UUID `json:"chat_id"`
}

type ChatMember struct {
	ChatID     uuid.UUID             `json:"chat_id"`
	UserID     uuid.UUID             `json:"user_id"`
	Role       sql.NullString        `json:"role"`
	MutedUntil sql.NullTime          `json:"muted_until"`
	IsBanned   sql.NullBool          `json:"is_banned"`
	LastReadAt sql.NullTime          `json:"last_read_at"`
	JoinedAt   sql.NullTime          `json:"joined_at"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
}

type Contact struct {
	UserID    uuid.UUID      `json:"user_id"`
	ContactID uuid.UUID      `json:"contact_id"`
	Nickname  sql.NullString `json:"nickname"`
	IsBlocked sql.NullBool   `json:"is_blocked"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Device struct {
	ID         uuid.UUID             `json:"id"`
	UserID     uuid.UUID             `json:"user_id"`
	PushToken  sql.NullString        `json:"push_token"`
	Platform   string                `json:"platform"`
	DeviceName sql.NullString        `json:"device_name"`
	LastActive sql.NullTime          `json:"last_active"`
	IsActive   sql.NullBool          `json:"is_active"`
	CreatedAt  sql.NullTime          `json:"created_at"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
}

type EncryptionKey struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	DeviceID  uuid.NullUUID  `json:"device_id"`
	PublicKey string         `json:"public_key"`
	KeyType   sql.NullString `json:"key_type"`
	IsUsed    sql.NullBool   `json:"is_used"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Medium struct {
	ID           uuid.UUID             `json:"id"`
	MessageID    uuid.NullUUID         `json:"message_id"`
	UploaderID   uuid.UUID             `json:"uploader_id"`
	Type         string                `json:"type"`
	Url          string                `json:"url"`
	ThumbnailUrl sql.NullString        `json:"thumbnail_url"`
	FileName     sql.NullString        `json:"file_name"`
	MimeType     sql.NullString        `json:"mime_type"`
	SizeBytes    sql.NullInt64         `json:"size_bytes"`
	Width        sql.NullInt32         `json:"width"`
	Height       sql.NullInt32         `json:"height"`
	Duration     sql.NullInt32         `json:"duration"`
	IsVoice      sql.NullBool          `json:"is_voice"`
	Waveform     []float64             `json:"waveform"`
	CreatedAt    sql.NullTime          `json:"created_at"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
}

type Message struct {
	ID              uuid.UUID             `json:"id"`
	ChatID          uuid.UUID             `json:"chat_id"`
	SenderID        uuid.UUID             `json:"sender_id"`
	ReplyToID       uuid.NullUUID         `json:"reply_to_id"`
	ThreadID        uuid.NullUUID         `json:"thread_id"`
	ForwardedFromID uuid.NullUUID         `json:"forwarded_from_id"`
	Type            sql.NullString        `json:"type"`
	Content         sql.NullString        `json:"content"`
	IsEncrypted     sql.NullBool          `json:"is_encrypted"`
	IsEdited        sql.NullBool          `json:"is_edited"`
	IsDeleted       sql.NullBool          `json:"is_deleted"`
	IsPinned        sql.NullBool          `json:"is_pinned"`
	ScheduledAt     sql.NullTime          `json:"scheduled_at"`
	ExpiresAt       sql.NullTime          `json:"expires_at"`
	ViewsCount      sql.NullInt32         `json:"views_count"`
	CreatedAt       sql.NullTime          `json:"created_at"`
	UpdatedAt       sql.NullTime          `json:"updated_at"`
	Metadata        pqtype.NullRawMessage `json:"metadata"`
}

type MessageStatus struct {
	MessageID   uuid.UUID    `json:"message_id"`
	UserID      uuid.UUID    `json:"user_id"`
	Delivered   sql.NullBool `json:"delivered"`
	Read        sql.NullBool `json:"read"`
	DeliveredAt sql.NullTime `json:"delivered_at"`
	ReadAt      sql.NullTime `json:"read_at"`
}

type Notification struct {
	ID            uuid.UUID             `json:"id"`
	UserID        uuid.UUID             `json:"user_id"`
	Type          string                `json:"type"`
	Title         sql.NullString        `json:"title"`
	Body          sql.NullString        `json:"body"`
	IsRead        sql.NullBool          `json:"is_read"`
	ReferenceID   uuid.NullUUID         `json:"reference_id"`
	ReferenceType sql.NullString        `json:"reference_type"`
	CreatedAt     sql.NullTime          `json:"created_at"`
	Metadata      pqtype.NullRawMessage `json:"metadata"`
}

type Poll struct {
	ID            uuid.UUID     `json:"id"`
	MessageID     uuid.UUID     `json:"message_id"`
	Question      string        `json:"question"`
	IsAnonymous   sql.NullBool  `json:"is_anonymous"`
	IsMultiple    sql.NullBool  `json:"is_multiple"`
	IsQuiz        sql.NullBool  `json:"is_quiz"`
	CorrectOption sql.NullInt32 `json:"correct_option"`
	ExpiresAt     sql.NullTime  `json:"expires_at"`
	CreatedAt     sql.NullTime  `json:"created_at"`
}

type PollOption struct {
	ID         uuid.UUID     `json:"id"`
	PollID     uuid.UUID     `json:"poll_id"`
	Text       string        `json:"text"`
	VotesCount sql.NullInt32 `json:"votes_count"`
	Position   int32         `json:"position"`
}

type PollVote struct {
	PollID    uuid.UUID    `json:"poll_id"`
	OptionID  uuid.UUID    `json:"option_id"`
	UserID    uuid.UUID    `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Reaction struct {
	MessageID uuid.UUID    `json:"message_id"`
	UserID    uuid.UUID    `json:"user_id"`
	Emoji     string       `json:"emoji"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID     `json:"id"`
	UserID       uuid.UUID     `json:"user_id"`
	DeviceID     uuid.NullUUID `json:"device_id"`
	RefreshToken string        `json:"refresh_token"`
	IpAddress    pqtype.Inet   `json:"ip_address"`
	ExpiresAt    time.Time     `json:"expires_at"`
	CreatedAt    sql.NullTime  `json:"created_at"`
}

type Sticker struct {
	ID        uuid.UUID      `json:"id"`
	PackID    uuid.UUID      `json:"pack_id"`
	Emoji     sql.NullString `json:"emoji"`
	Url       string         `json:"url"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type StickerPack struct {
	ID         uuid.UUID     `json:"id"`
	Name       string        `json:"name"`
	AuthorID   uuid.NullUUID `json:"author_id"`
	IsOfficial sql.NullBool  `json:"is_official"`
	CreatedAt  sql.NullTime  `json:"created_at"`
}

type Story struct {
	ID           uuid.UUID             `json:"id"`
	UserID       uuid.UUID             `json:"user_id"`
	MediaUrl     string                `json:"media_url"`
	ThumbnailUrl sql.NullString        `json:"thumbnail_url"`
	Type         sql.NullString        `json:"type"`
	Caption      sql.NullString        `json:"caption"`
	ViewsCount   sql.NullInt32         `json:"views_count"`
	ExpiresAt    sql.NullTime          `json:"expires_at"`
	CreatedAt    sql.NullTime          `json:"created_at"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
}

type StoryView struct {
	StoryID  uuid.UUID    `json:"story_id"`
	UserID   uuid.UUID    `json:"user_id"`
	ViewedAt sql.NullTime `json:"viewed_at"`
}

type User struct {
	ID         uuid.UUID             `json:"id"`
	Username   string                `json:"username"`
	Phone      sql.NullString        `json:"phone"`
	Email      sql.NullString        `json:"email"`
	Password   string                `json:"password"`
	AvatarUrl  sql.NullString        `json:"avatar_url"`
	Bio        sql.NullString        `json:"bio"`
	IsOnline   sql.NullBool          `json:"is_online"`
	LastSeen   sql.NullTime          `json:"last_seen"`
	IsVerified sql.NullBool          `json:"is_verified"`
	IsBot      sql.NullBool          `json:"is_bot"`
	IsDeleted  sql.NullBool          `json:"is_deleted"`
	DeleteAt   sql.NullTime          `json:"delete_at"`
	Language   sql.NullString        `json:"language"`
	CreatedAt  sql.NullTime          `json:"created_at"`
	UpdatedAt  sql.NullTime          `json:"updated_at"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
}

type UserStickerPack struct {
	UserID  uuid.UUID    `json:"user_id"`
	PackID  uuid.UUID    `json:"pack_id"`
	AddedAt sql.NullTime `json:"added_at"`
}
