// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type MediaStatus string

const (
	MediaStatusPending   MediaStatus = "pending"
	MediaStatusUploaded  MediaStatus = "uploaded"
	MediaStatusProcessed MediaStatus = "processed"
	MediaStatusFailed    MediaStatus = "failed"
)

func (e *MediaStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaStatus(s)
	case string:
		*e = MediaStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaStatus: %T", src)
	}
	return nil
}

type NullMediaStatus struct {
	MediaStatus MediaStatus `json:"media_status"`
	Valid       bool        `json:"valid"` // Valid is true if MediaStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MediaStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaStatus), nil
}

type MediaType string

const (
	MediaTypeImage   MediaType = "image"
	MediaTypeVideo   MediaType = "video"
	MediaTypeAudio   MediaType = "audio"
	MediaTypeFile    MediaType = "file"
	MediaTypeVoice   MediaType = "voice"
	MediaTypeSticker MediaType = "sticker"
	MediaTypeGif     MediaType = "gif"
)

func (e *MediaType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaType(s)
	case string:
		*e = MediaType(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaType: %T", src)
	}
	return nil
}

type NullMediaType struct {
	MediaType MediaType `json:"media_type"`
	Valid     bool      `json:"valid"` // Valid is true if MediaType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaType) Scan(value interface{}) error {
	if value == nil {
		ns.MediaType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaType), nil
}

type AiRequest struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	RequestType string    `json:"request_type"`
	TokensUsed  int32     `json:"tokens_used"`
	CreatedAt   time.Time `json:"created_at"`
}

type AnimatedEmoji struct {
	ID        int32         `json:"id"`
	Emoji     string        `json:"emoji"`
	ObjectKey string        `json:"object_key"`
	Bucket    string        `json:"bucket"`
	Width     sql.NullInt32 `json:"width"`
	Height    sql.NullInt32 `json:"height"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type AuditLog struct {
	ID         uuid.UUID             `json:"id"`
	ActorID    uuid.NullUUID         `json:"actor_id"`
	Action     string                `json:"action"`
	TargetType sql.NullString        `json:"target_type"`
	TargetID   uuid.NullUUID         `json:"target_id"`
	IpAddress  pqtype.Inet           `json:"ip_address"`
	UserAgent  sql.NullString        `json:"user_agent"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	CreatedAt  sql.NullTime          `json:"created_at"`
}

type Bot struct {
	ID            uuid.UUID `json:"id"`
	OwnerID       uuid.UUID `json:"owner_id"`
	Token         string    `json:"token"`
	Username      string    `json:"username"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	AvatarUrl     string    `json:"avatar_url"`
	IsActive      bool      `json:"is_active"`
	IsAiEnabled   bool      `json:"is_ai_enabled"`
	WebhookUrl    string    `json:"webhook_url"`
	WebhookSecret string    `json:"webhook_secret"`
	CreatedAt     time.Time `json:"created_at"`
}

type BotCommand struct {
	ID          uuid.UUID `json:"id"`
	BotID       uuid.UUID `json:"bot_id"`
	Command     string    `json:"command"`
	Description string    `json:"description"`
}

type BotUpdate struct {
	ID        int64           `json:"id"`
	BotID     uuid.UUID       `json:"bot_id"`
	UpdateID  int64           `json:"update_id"`
	Type      string          `json:"type"`
	Payload   json.RawMessage `json:"payload"`
	Processed bool            `json:"processed"`
	CreatedAt time.Time       `json:"created_at"`
}

type BusinessProfile struct {
	UserID       uuid.UUID       `json:"user_id"`
	BusinessName string          `json:"business_name"`
	Category     string          `json:"category"`
	Description  string          `json:"description"`
	Address      string          `json:"address"`
	Email        string          `json:"email"`
	Website      string          `json:"website"`
	PhonePublic  string          `json:"phone_public"`
	WorkingHours json.RawMessage `json:"working_hours"`
	IsVerified   bool            `json:"is_verified"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type Call struct {
	ID          uuid.UUID             `json:"id"`
	ChatID      uuid.NullUUID         `json:"chat_id"`
	InitiatorID uuid.UUID             `json:"initiator_id"`
	Type        string                `json:"type"`
	Status      string                `json:"status"`
	StartedAt   sql.NullTime          `json:"started_at"`
	EndedAt     sql.NullTime          `json:"ended_at"`
	Duration    sql.NullInt32         `json:"duration"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
}

type CallParticipant struct {
	CallID     uuid.UUID    `json:"call_id"`
	UserID     uuid.UUID    `json:"user_id"`
	JoinedAt   sql.NullTime `json:"joined_at"`
	LeftAt     sql.NullTime `json:"left_at"`
	IsMuted    sql.NullBool `json:"is_muted"`
	IsVideoOff sql.NullBool `json:"is_video_off"`
}

type ChannelStat struct {
	ChannelID   uuid.UUID     `json:"channel_id"`
	Date        time.Time     `json:"date"`
	Views       sql.NullInt32 `json:"views"`
	Shares      sql.NullInt32 `json:"shares"`
	NewMembers  sql.NullInt32 `json:"new_members"`
	LeftMembers sql.NullInt32 `json:"left_members"`
}

type Chat struct {
	ID          uuid.UUID             `json:"id"`
	Type        string                `json:"type"`
	Name        sql.NullString        `json:"name"`
	Username    sql.NullString        `json:"username"`
	AvatarUrl   sql.NullString        `json:"avatar_url"`
	Description sql.NullString        `json:"description"`
	OwnerID     uuid.NullUUID         `json:"owner_id"`
	IsPublic    sql.NullBool          `json:"is_public"`
	IsDeleted   sql.NullBool          `json:"is_deleted"`
	SlowMode    sql.NullInt32         `json:"slow_mode"`
	MemberCount sql.NullInt32         `json:"member_count"`
	InviteLink  sql.NullString        `json:"invite_link"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	UpdatedAt   sql.NullTime          `json:"updated_at"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
}

type ChatFolder struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	Name      string         `json:"name"`
	Emoji     sql.NullString `json:"emoji"`
	Position  sql.NullInt32  `json:"position"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type ChatFolderItem struct {
	FolderID uuid.UUID `json:"folder_id"`
	ChatID   uuid.UUID `json:"chat_id"`
}

type ChatLabel struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ChatID    uuid.UUID `json:"chat_id"`
	Label     string    `json:"label"`
	Color     string    `json:"color"`
	CreatedAt time.Time `json:"created_at"`
}

type ChatMember struct {
	ChatID     uuid.UUID             `json:"chat_id"`
	UserID     uuid.UUID             `json:"user_id"`
	Role       sql.NullString        `json:"role"`
	MutedUntil sql.NullTime          `json:"muted_until"`
	IsBanned   sql.NullBool          `json:"is_banned"`
	LastReadAt sql.NullTime          `json:"last_read_at"`
	JoinedAt   sql.NullTime          `json:"joined_at"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	IsArchived sql.NullBool          `json:"is_archived"`
}

type ChatTopic struct {
	ID           uuid.UUID      `json:"id"`
	ChatID       uuid.UUID      `json:"chat_id"`
	Name         string         `json:"name"`
	IconEmoji    sql.NullString `json:"icon_emoji"`
	IconColor    sql.NullString `json:"icon_color"`
	CreatedBy    uuid.NullUUID  `json:"created_by"`
	IsClosed     sql.NullBool   `json:"is_closed"`
	IsHidden     sql.NullBool   `json:"is_hidden"`
	MessageCount sql.NullInt32  `json:"message_count"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type CloseFriend struct {
	UserID    uuid.UUID `json:"user_id"`
	FriendID  uuid.UUID `json:"friend_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Contact struct {
	UserID    uuid.UUID      `json:"user_id"`
	ContactID uuid.UUID      `json:"contact_id"`
	Nickname  sql.NullString `json:"nickname"`
	IsBlocked sql.NullBool   `json:"is_blocked"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type DeletedMessage struct {
	MessageID uuid.UUID    `json:"message_id"`
	CreatedAt time.Time    `json:"created_at"`
	UserID    uuid.UUID    `json:"user_id"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Device struct {
	ID         uuid.UUID             `json:"id"`
	UserID     uuid.UUID             `json:"user_id"`
	PushToken  sql.NullString        `json:"push_token"`
	Platform   string                `json:"platform"`
	DeviceName sql.NullString        `json:"device_name"`
	LastActive sql.NullTime          `json:"last_active"`
	IsActive   sql.NullBool          `json:"is_active"`
	CreatedAt  sql.NullTime          `json:"created_at"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
}

type EmojiKeyword struct {
	ID      int32          `json:"id"`
	Keyword string         `json:"keyword"`
	Emoji   string         `json:"emoji"`
	Lang    sql.NullString `json:"lang"`
	Weight  sql.NullInt32  `json:"weight"`
}

type IdentityKey struct {
	ID             uuid.UUID     `json:"id"`
	UserID         uuid.UUID     `json:"user_id"`
	DeviceID       uuid.NullUUID `json:"device_id"`
	PublicKey      string        `json:"public_key"`
	RegistrationID int32         `json:"registration_id"`
	CreatedAt      sql.NullTime  `json:"created_at"`
}

type InviteLink struct {
	ID        uuid.UUID     `json:"id"`
	Code      string        `json:"code"`
	ChatID    uuid.UUID     `json:"chat_id"`
	CreatedBy uuid.UUID     `json:"created_by"`
	MaxUses   sql.NullInt32 `json:"max_uses"`
	UsesCount sql.NullInt32 `json:"uses_count"`
	ExpiresAt sql.NullTime  `json:"expires_at"`
	IsRevoked sql.NullBool  `json:"is_revoked"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type KeyBundle struct {
	UserID    uuid.UUID       `json:"user_id"`
	DeviceID  uuid.UUID       `json:"device_id"`
	Bundle    json.RawMessage `json:"bundle"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
}

type LinkPreview struct {
	ID          uuid.UUID      `json:"id"`
	Url         string         `json:"url"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
	SiteName    sql.NullString `json:"site_name"`
	FetchedAt   sql.NullTime   `json:"fetched_at"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
}

type LiveLocation struct {
	ID        uuid.UUID       `json:"id"`
	UserID    uuid.UUID       `json:"user_id"`
	ChatID    uuid.UUID       `json:"chat_id"`
	MessageID uuid.NullUUID   `json:"message_id"`
	Latitude  float64         `json:"latitude"`
	Longitude float64         `json:"longitude"`
	Heading   sql.NullInt32   `json:"heading"`
	Accuracy  sql.NullFloat64 `json:"accuracy"`
	ExpiresAt time.Time       `json:"expires_at"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
	CreatedAt sql.NullTime    `json:"created_at"`
}

type MediaSearchIndex struct {
	ID        uuid.UUID      `json:"id"`
	MediaID   uuid.UUID      `json:"media_id"`
	MessageID uuid.NullUUID  `json:"message_id"`
	CreatedAt time.Time      `json:"created_at"`
	Content   string         `json:"content"`
	Source    string         `json:"source"`
	Lang      sql.NullString `json:"lang"`
	IndexedAt sql.NullTime   `json:"indexed_at"`
}

type Medium struct {
	ID           uuid.UUID             `json:"id"`
	UploaderID   uuid.UUID             `json:"uploader_id"`
	Type         MediaType             `json:"type"`
	Status       MediaStatus           `json:"status"`
	Bucket       string                `json:"bucket"`
	ObjectKey    string                `json:"object_key"`
	OriginalName sql.NullString        `json:"original_name"`
	MimeType     string                `json:"mime_type"`
	SizeBytes    sql.NullInt64         `json:"size_bytes"`
	Width        sql.NullInt32         `json:"width"`
	Height       sql.NullInt32         `json:"height"`
	DurationSec  sql.NullFloat64       `json:"duration_sec"`
	ThumbKey     sql.NullString        `json:"thumb_key"`
	Waveform     pqtype.NullRawMessage `json:"waveform"`
	BlurHash     sql.NullString        `json:"blur_hash"`
	CreatedAt    time.Time             `json:"created_at"`
	ExpiresAt    sql.NullTime          `json:"expires_at"`
}

type Message struct {
	ID              uuid.UUID             `json:"id"`
	ChatID          uuid.UUID             `json:"chat_id"`
	SenderID        uuid.UUID             `json:"sender_id"`
	ReplyToID       uuid.NullUUID         `json:"reply_to_id"`
	ThreadID        uuid.NullUUID         `json:"thread_id"`
	ForwardedFromID uuid.NullUUID         `json:"forwarded_from_id"`
	Type            sql.NullString        `json:"type"`
	Content         string                `json:"content"`
	IsEncrypted     sql.NullBool          `json:"is_encrypted"`
	IsEdited        sql.NullBool          `json:"is_edited"`
	IsDeleted       sql.NullBool          `json:"is_deleted"`
	IsPinned        sql.NullBool          `json:"is_pinned"`
	ScheduledAt     sql.NullTime          `json:"scheduled_at"`
	ExpiresAt       sql.NullTime          `json:"expires_at"`
	ViewsCount      sql.NullInt32         `json:"views_count"`
	CreatedAt       time.Time             `json:"created_at"`
	UpdatedAt       sql.NullTime          `json:"updated_at"`
	Metadata        pqtype.NullRawMessage `json:"metadata"`
	TopicID         uuid.NullUUID         `json:"topic_id"`
	MediaID         uuid.NullUUID         `json:"media_id"`
	Format          sql.NullString        `json:"format"`
	IsSpoiler       sql.NullBool          `json:"is_spoiler"`
	QuotedText      sql.NullString        `json:"quoted_text"`
	QuotedOffset    sql.NullInt32         `json:"quoted_offset"`
	QuotedLength    sql.NullInt32         `json:"quoted_length"`
	ForwardSenderID uuid.NullUUID         `json:"forward_sender_id"`
	ForwardChatID   uuid.NullUUID         `json:"forward_chat_id"`
	ForwardDate     sql.NullTime          `json:"forward_date"`
	Geo             pqtype.NullRawMessage `json:"geo"`
	LinkPreview     pqtype.NullRawMessage `json:"link_preview"`
}

type MessageEdit struct {
	ID         uuid.UUID    `json:"id"`
	MessageID  uuid.UUID    `json:"message_id"`
	CreatedAt  time.Time    `json:"created_at"`
	OldContent string       `json:"old_content"`
	EditedAt   sql.NullTime `json:"edited_at"`
	EditNumber int32        `json:"edit_number"`
}

type MessageReminder struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	MessageID uuid.UUID    `json:"message_id"`
	CreatedAt time.Time    `json:"created_at"`
	RemindAt  time.Time    `json:"remind_at"`
	IsSent    sql.NullBool `json:"is_sent"`
}

type MessageStatus struct {
	MessageID uuid.UUID `json:"message_id"`
	CreatedAt time.Time `json:"created_at"`
	UserID    uuid.UUID `json:"user_id"`
	Status    string    `json:"status"`
}

type Notification struct {
	ID            uuid.UUID             `json:"id"`
	UserID        uuid.UUID             `json:"user_id"`
	Type          string                `json:"type"`
	Title         sql.NullString        `json:"title"`
	Body          sql.NullString        `json:"body"`
	IsRead        sql.NullBool          `json:"is_read"`
	ReferenceID   uuid.NullUUID         `json:"reference_id"`
	ReferenceType sql.NullString        `json:"reference_type"`
	CreatedAt     sql.NullTime          `json:"created_at"`
	Metadata      pqtype.NullRawMessage `json:"metadata"`
}

type OauthAccount struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.UUID      `json:"user_id"`
	Provider   string         `json:"provider"`
	ProviderID string         `json:"provider_id"`
	Email      sql.NullString `json:"email"`
	AvatarUrl  sql.NullString `json:"avatar_url"`
	CreatedAt  time.Time      `json:"created_at"`
}

type OneTimePrekey struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.UUID     `json:"user_id"`
	DeviceID  uuid.NullUUID `json:"device_id"`
	KeyID     int32         `json:"key_id"`
	PublicKey string        `json:"public_key"`
	IsUsed    sql.NullBool  `json:"is_used"`
	UsedAt    sql.NullTime  `json:"used_at"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Passkey struct {
	ID           uuid.UUID    `json:"id"`
	UserID       uuid.UUID    `json:"user_id"`
	CredentialID string       `json:"credential_id"`
	PublicKey    []byte       `json:"public_key"`
	Aaguid       []byte       `json:"aaguid"`
	SignCount    int64        `json:"sign_count"`
	Name         string       `json:"name"`
	CreatedAt    time.Time    `json:"created_at"`
	LastUsedAt   sql.NullTime `json:"last_used_at"`
}

type Payment struct {
	ID          uuid.UUID       `json:"id"`
	BotID       uuid.UUID       `json:"bot_id"`
	UserID      uuid.UUID       `json:"user_id"`
	Amount      int64           `json:"amount"`
	Currency    string          `json:"currency"`
	Status      string          `json:"status"`
	StripeID    string          `json:"stripe_id"`
	Description string          `json:"description"`
	Metadata    json.RawMessage `json:"metadata"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type PinnedMessage struct {
	ChatID    uuid.UUID    `json:"chat_id"`
	MessageID uuid.UUID    `json:"message_id"`
	CreatedAt time.Time    `json:"created_at"`
	PinnedBy  uuid.UUID    `json:"pinned_by"`
	PinnedAt  sql.NullTime `json:"pinned_at"`
}

type Poll struct {
	ID        uuid.UUID       `json:"id"`
	MessageID uuid.UUID       `json:"message_id"`
	CreatedAt time.Time       `json:"created_at"`
	Question  string          `json:"question"`
	Options   json.RawMessage `json:"options"`
	Votes     json.RawMessage `json:"votes"`
	IsClosed  sql.NullBool    `json:"is_closed"`
}

type PollOption struct {
	ID         uuid.UUID     `json:"id"`
	PollID     uuid.UUID     `json:"poll_id"`
	Text       string        `json:"text"`
	VotesCount sql.NullInt32 `json:"votes_count"`
	Position   int32         `json:"position"`
}

type PollVote struct {
	PollID    uuid.UUID    `json:"poll_id"`
	OptionID  uuid.UUID    `json:"option_id"`
	UserID    uuid.UUID    `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type PremiumSetting struct {
	UserID             uuid.UUID `json:"user_id"`
	HidePhone          bool      `json:"hide_phone"`
	AwayMessage        string    `json:"away_message"`
	AwayMessageEnabled bool      `json:"away_message_enabled"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type QuickReply struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Shortcut  string       `json:"shortcut"`
	Text      string       `json:"text"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type RateLimit struct {
	Key         string        `json:"key"`
	Count       sql.NullInt32 `json:"count"`
	WindowStart time.Time     `json:"window_start"`
}

type Reaction struct {
	MessageID uuid.UUID    `json:"message_id"`
	CreatedAt time.Time    `json:"created_at"`
	UserID    uuid.UUID    `json:"user_id"`
	Emoji     string       `json:"emoji"`
	ReactedAt sql.NullTime `json:"reacted_at"`
}

type RecoveryRequest struct {
	ID              uuid.UUID             `json:"id"`
	SessionID       uuid.UUID             `json:"session_id"`
	RequesterID     uuid.UUID             `json:"requester_id"`
	Status          sql.NullString        `json:"status"`
	CollectedShares pqtype.NullRawMessage `json:"collected_shares"`
	CreatedAt       sql.NullTime          `json:"created_at"`
	ExpiresAt       sql.NullTime          `json:"expires_at"`
}

type RecoverySession struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	Threshold       int32          `json:"threshold"`
	TotalShares     int32          `json:"total_shares"`
	Status          sql.NullString `json:"status"`
	EncryptedSecret string         `json:"encrypted_secret"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	ExpiresAt       sql.NullTime   `json:"expires_at"`
}

type RecoveryShare struct {
	ID          uuid.UUID    `json:"id"`
	SessionID   uuid.UUID    `json:"session_id"`
	GuardianID  uuid.UUID    `json:"guardian_id"`
	ShareIndex  int32        `json:"share_index"`
	ShareData   string       `json:"share_data"`
	IsSubmitted sql.NullBool `json:"is_submitted"`
	SubmittedAt sql.NullTime `json:"submitted_at"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type Report struct {
	ID                int64          `json:"id"`
	ReporterID        uuid.UUID      `json:"reporter_id"`
	ReportedUserID    uuid.UUID      `json:"reported_user_id"`
	ReportedMessageID sql.NullInt64  `json:"reported_message_id"`
	Reason            string         `json:"reason"`
	Description       sql.NullString `json:"description"`
	Status            sql.NullString `json:"status"`
	ReviewedBy        uuid.NullUUID  `json:"reviewed_by"`
	ReviewedAt        sql.NullTime   `json:"reviewed_at"`
	CreatedAt         sql.NullTime   `json:"created_at"`
}

type SavedMessage struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	MessageID uuid.UUID    `json:"message_id"`
	CreatedAt time.Time    `json:"created_at"`
	SavedAt   sql.NullTime `json:"saved_at"`
}

type Session struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	DeviceID     uuid.NullUUID  `json:"device_id"`
	RefreshToken string         `json:"refresh_token"`
	IpAddress    pqtype.Inet    `json:"ip_address"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UserAgent    sql.NullString `json:"user_agent"`
	Fingerprint  sql.NullString `json:"fingerprint"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SignedPrekey struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.UUID     `json:"user_id"`
	DeviceID  uuid.NullUUID `json:"device_id"`
	KeyID     int32         `json:"key_id"`
	PublicKey string        `json:"public_key"`
	Signature string        `json:"signature"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Sticker struct {
	ID        uuid.UUID      `json:"id"`
	PackID    uuid.UUID      `json:"pack_id"`
	Emoji     sql.NullString `json:"emoji"`
	Url       string         `json:"url"`
	CreatedAt sql.NullTime   `json:"created_at"`
	MediaID   uuid.NullUUID  `json:"media_id"`
	Position  sql.NullInt32  `json:"position"`
	Format    sql.NullString `json:"format"`
	LottieUrl sql.NullString `json:"lottie_url"`
}

type StickerPack struct {
	ID         uuid.UUID      `json:"id"`
	Name       string         `json:"name"`
	AuthorID   uuid.NullUUID  `json:"author_id"`
	IsOfficial sql.NullBool   `json:"is_official"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	ThumbUrl   sql.NullString `json:"thumb_url"`
	IsPremium  sql.NullBool   `json:"is_premium"`
}

type Story struct {
	ID           uuid.UUID             `json:"id"`
	UserID       uuid.UUID             `json:"user_id"`
	MediaUrl     string                `json:"media_url"`
	ThumbnailUrl sql.NullString        `json:"thumbnail_url"`
	Type         sql.NullString        `json:"type"`
	Caption      sql.NullString        `json:"caption"`
	ViewsCount   sql.NullInt32         `json:"views_count"`
	ExpiresAt    sql.NullTime          `json:"expires_at"`
	CreatedAt    sql.NullTime          `json:"created_at"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	IsArchived   sql.NullBool          `json:"is_archived"`
	Audience     sql.NullString        `json:"audience"`
	MediaID      uuid.NullUUID         `json:"media_id"`
	StickerData  pqtype.NullRawMessage `json:"sticker_data"`
	MusicData    pqtype.NullRawMessage `json:"music_data"`
}

type StoryArchive struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	StoryID    uuid.UUID `json:"story_id"`
	ArchivedAt time.Time `json:"archived_at"`
}

type StoryReaction struct {
	ID        uuid.UUID `json:"id"`
	StoryID   uuid.UUID `json:"story_id"`
	UserID    uuid.UUID `json:"user_id"`
	Emoji     string    `json:"emoji"`
	CreatedAt time.Time `json:"created_at"`
}

type StoryView struct {
	StoryID  uuid.UUID    `json:"story_id"`
	UserID   uuid.UUID    `json:"user_id"`
	ViewedAt sql.NullTime `json:"viewed_at"`
}

type Subscription struct {
	ID                uuid.UUID             `json:"id"`
	UserID            uuid.UUID             `json:"user_id"`
	Plan              string                `json:"plan"`
	Status            string                `json:"status"`
	StartedAt         sql.NullTime          `json:"started_at"`
	ExpiresAt         sql.NullTime          `json:"expires_at"`
	AutoRenew         sql.NullBool          `json:"auto_renew"`
	PaymentRef        sql.NullString        `json:"payment_ref"`
	Metadata          pqtype.NullRawMessage `json:"metadata"`
	StripeCustomerID  string                `json:"stripe_customer_id"`
	StripeSubID       string                `json:"stripe_sub_id"`
	CurrentPeriodEnd  sql.NullTime          `json:"current_period_end"`
	CancelAtPeriodEnd bool                  `json:"cancel_at_period_end"`
	UpdatedAt         time.Time             `json:"updated_at"`
}

type User struct {
	ID              uuid.UUID             `json:"id"`
	Username        string                `json:"username"`
	Phone           sql.NullString        `json:"phone"`
	Email           sql.NullString        `json:"email"`
	Password        string                `json:"password"`
	AvatarUrl       sql.NullString        `json:"avatar_url"`
	Bio             sql.NullString        `json:"bio"`
	IsOnline        sql.NullBool          `json:"is_online"`
	LastSeen        sql.NullTime          `json:"last_seen"`
	IsVerified      sql.NullBool          `json:"is_verified"`
	IsBot           sql.NullBool          `json:"is_bot"`
	IsDeleted       sql.NullBool          `json:"is_deleted"`
	DeleteAt        sql.NullTime          `json:"delete_at"`
	Language        sql.NullString        `json:"language"`
	CreatedAt       sql.NullTime          `json:"created_at"`
	UpdatedAt       sql.NullTime          `json:"updated_at"`
	Metadata        pqtype.NullRawMessage `json:"metadata"`
	TotpSecret      sql.NullString        `json:"totp_secret"`
	TotpPending     sql.NullString        `json:"totp_pending"`
	TotpBackup      []string              `json:"totp_backup"`
	IsPremium       sql.NullBool          `json:"is_premium"`
	PremiumUntil    sql.NullTime          `json:"premium_until"`
	LastSeenPrivacy sql.NullString        `json:"last_seen_privacy"`
	OnlinePrivacy   sql.NullString        `json:"online_privacy"`
	BirthYear       sql.NullInt32         `json:"birth_year"`
	AcceptedTerms   sql.NullBool          `json:"accepted_terms"`
	TermsAcceptedAt sql.NullTime          `json:"terms_accepted_at"`
}

type UserBan struct {
	ID        int64         `json:"id"`
	UserID    uuid.UUID     `json:"user_id"`
	BannedBy  uuid.NullUUID `json:"banned_by"`
	Reason    string        `json:"reason"`
	Permanent sql.NullBool  `json:"permanent"`
	ExpiresAt sql.NullTime  `json:"expires_at"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type UserBlock struct {
	ID        int64        `json:"id"`
	BlockerID uuid.UUID    `json:"blocker_id"`
	BlockedID uuid.UUID    `json:"blocked_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type UserStickerPack struct {
	UserID   uuid.UUID     `json:"user_id"`
	PackID   uuid.UUID     `json:"pack_id"`
	AddedAt  sql.NullTime  `json:"added_at"`
	Position sql.NullInt32 `json:"position"`
}

type VoiceRoom struct {
	ID        uuid.UUID      `json:"id"`
	ChatID    uuid.UUID      `json:"chat_id"`
	Name      string         `json:"name"`
	Type      sql.NullString `json:"type"`
	UserLimit sql.NullInt32  `json:"user_limit"`
	IsActive  sql.NullBool   `json:"is_active"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type VoiceRoomParticipant struct {
	RoomID     uuid.UUID    `json:"room_id"`
	UserID     uuid.UUID    `json:"user_id"`
	IsMuted    sql.NullBool `json:"is_muted"`
	IsDeafened sql.NullBool `json:"is_deafened"`
	IsVideo    sql.NullBool `json:"is_video"`
	IsSpeaking sql.NullBool `json:"is_speaking"`
	JoinedAt   sql.NullTime `json:"joined_at"`
}
