// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getOAuthAccounts = `-- name: GetOAuthAccounts :many
SELECT provider, provider_id, email, avatar_url, created_at
FROM oauth_accounts
WHERE user_id = $1
ORDER BY created_at
`

type GetOAuthAccountsRow struct {
	Provider   string         `json:"provider"`
	ProviderID string         `json:"provider_id"`
	Email      sql.NullString `json:"email"`
	AvatarUrl  sql.NullString `json:"avatar_url"`
	CreatedAt  time.Time      `json:"created_at"`
}

func (q *Queries) GetOAuthAccounts(ctx context.Context, userID uuid.UUID) ([]GetOAuthAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOAuthAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOAuthAccountsRow
	for rows.Next() {
		var i GetOAuthAccountsRow
		if err := rows.Scan(
			&i.Provider,
			&i.ProviderID,
			&i.Email,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByOAuth = `-- name: GetUserByOAuth :one
SELECT u.id, u.username, u.phone, u.email, u.password, u.avatar_url, u.bio, u.is_online, u.last_seen, u.is_verified, u.is_bot, u.is_deleted, u.delete_at, u.language, u.created_at, u.updated_at, u.metadata, u.totp_secret, u.totp_pending, u.totp_backup, u.is_premium, u.premium_until, u.last_seen_privacy, u.online_privacy, u.birth_year, u.accepted_terms, u.terms_accepted_at FROM users u
JOIN oauth_accounts oa ON oa.user_id = u.id
WHERE oa.provider = $1 AND oa.provider_id = $2
LIMIT 1
`

type GetUserByOAuthParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) GetUserByOAuth(ctx context.Context, arg GetUserByOAuthParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByOAuth, arg.Provider, arg.ProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Email,
		&i.Password,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsOnline,
		&i.LastSeen,
		&i.IsVerified,
		&i.IsBot,
		&i.IsDeleted,
		&i.DeleteAt,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
		&i.TotpSecret,
		&i.TotpPending,
		pq.Array(&i.TotpBackup),
		&i.IsPremium,
		&i.PremiumUntil,
		&i.LastSeenPrivacy,
		&i.OnlinePrivacy,
		&i.BirthYear,
		&i.AcceptedTerms,
		&i.TermsAcceptedAt,
	)
	return i, err
}

const linkOAuthAccount = `-- name: LinkOAuthAccount :exec
INSERT INTO oauth_accounts (user_id, provider, provider_id, email, avatar_url)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (provider, provider_id) DO UPDATE
    SET email      = EXCLUDED.email,
        avatar_url = EXCLUDED.avatar_url
`

type LinkOAuthAccountParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	Provider   string         `json:"provider"`
	ProviderID string         `json:"provider_id"`
	Email      sql.NullString `json:"email"`
	AvatarUrl  sql.NullString `json:"avatar_url"`
}

func (q *Queries) LinkOAuthAccount(ctx context.Context, arg LinkOAuthAccountParams) error {
	_, err := q.db.ExecContext(ctx, linkOAuthAccount,
		arg.UserID,
		arg.Provider,
		arg.ProviderID,
		arg.Email,
		arg.AvatarUrl,
	)
	return err
}

const unlinkOAuthAccount = `-- name: UnlinkOAuthAccount :exec
DELETE FROM oauth_accounts
WHERE user_id = $1 AND provider = $2
`

type UnlinkOAuthAccountParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) UnlinkOAuthAccount(ctx context.Context, arg UnlinkOAuthAccountParams) error {
	_, err := q.db.ExecContext(ctx, unlinkOAuthAccount, arg.UserID, arg.Provider)
	return err
}
