// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ocr.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createMediaSearchIndex = `-- name: CreateMediaSearchIndex :exec
INSERT INTO media_search_index (media_id, message_id, content, source, lang)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type CreateMediaSearchIndexParams struct {
	MediaID   uuid.UUID      `json:"media_id"`
	MessageID uuid.NullUUID  `json:"message_id"`
	Content   string         `json:"content"`
	Source    string         `json:"source"`
	Lang      sql.NullString `json:"lang"`
}

func (q *Queries) CreateMediaSearchIndex(ctx context.Context, arg CreateMediaSearchIndexParams) error {
	_, err := q.db.ExecContext(ctx, createMediaSearchIndex,
		arg.MediaID,
		arg.MessageID,
		arg.Content,
		arg.Source,
		arg.Lang,
	)
	return err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, uploader_id, type, status, bucket, object_key, original_name, mime_type, size_bytes, width, height, duration_sec, thumb_key, waveform, blur_hash, created_at, expires_at FROM media WHERE id = $1
`

func (q *Queries) GetMediaByID(ctx context.Context, id uuid.UUID) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.Type,
		&i.Status,
		&i.Bucket,
		&i.ObjectKey,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.DurationSec,
		&i.ThumbKey,
		&i.Waveform,
		&i.BlurHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getMediaSearchIndex = `-- name: GetMediaSearchIndex :one
SELECT id, media_id, message_id, created_at, content, source, lang, indexed_at FROM media_search_index
WHERE media_id = $1
LIMIT 1
`

func (q *Queries) GetMediaSearchIndex(ctx context.Context, mediaID uuid.UUID) (MediaSearchIndex, error) {
	row := q.db.QueryRowContext(ctx, getMediaSearchIndex, mediaID)
	var i MediaSearchIndex
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.MessageID,
		&i.CreatedAt,
		&i.Content,
		&i.Source,
		&i.Lang,
		&i.IndexedAt,
	)
	return i, err
}
