// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const addChatLabel = `-- name: AddChatLabel :one
INSERT INTO chat_labels (user_id, chat_id, label, color)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, chat_id, label) DO UPDATE SET color = EXCLUDED.color
RETURNING id, user_id, chat_id, label, color, created_at
`

type AddChatLabelParams struct {
	UserID uuid.UUID `json:"user_id"`
	ChatID uuid.UUID `json:"chat_id"`
	Label  string    `json:"label"`
	Color  string    `json:"color"`
}

func (q *Queries) AddChatLabel(ctx context.Context, arg AddChatLabelParams) (ChatLabel, error) {
	row := q.db.QueryRowContext(ctx, addChatLabel,
		arg.UserID,
		arg.ChatID,
		arg.Label,
		arg.Color,
	)
	var i ChatLabel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChatID,
		&i.Label,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (bot_id, user_id, amount, currency, description, stripe_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, bot_id, user_id, amount, currency, status, stripe_id, description, metadata, created_at, updated_at
`

type CreatePaymentParams struct {
	BotID       uuid.UUID `json:"bot_id"`
	UserID      uuid.UUID `json:"user_id"`
	Amount      int64     `json:"amount"`
	Currency    string    `json:"currency"`
	Description string    `json:"description"`
	StripeID    string    `json:"stripe_id"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.BotID,
		arg.UserID,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.StripeID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.StripeID,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChatLabel = `-- name: DeleteChatLabel :exec
DELETE FROM chat_labels WHERE id = $1 AND user_id = $2
`

type DeleteChatLabelParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteChatLabel(ctx context.Context, arg DeleteChatLabelParams) error {
	_, err := q.db.ExecContext(ctx, deleteChatLabel, arg.ID, arg.UserID)
	return err
}

const getBotPayments = `-- name: GetBotPayments :many
SELECT id, bot_id, user_id, amount, currency, status, stripe_id, description, metadata, created_at, updated_at FROM payments
WHERE bot_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetBotPaymentsParams struct {
	BotID  uuid.UUID `json:"bot_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetBotPayments(ctx context.Context, arg GetBotPaymentsParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, getBotPayments, arg.BotID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.UserID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.StripeID,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBusinessProfile = `-- name: GetBusinessProfile :one
SELECT user_id, business_name, category, description, address, email, website, phone_public, working_hours, is_verified, created_at, updated_at FROM business_profiles WHERE user_id = $1
`

func (q *Queries) GetBusinessProfile(ctx context.Context, userID uuid.UUID) (BusinessProfile, error) {
	row := q.db.QueryRowContext(ctx, getBusinessProfile, userID)
	var i BusinessProfile
	err := row.Scan(
		&i.UserID,
		&i.BusinessName,
		&i.Category,
		&i.Description,
		&i.Address,
		&i.Email,
		&i.Website,
		&i.PhonePublic,
		&i.WorkingHours,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatLabels = `-- name: GetChatLabels :many
SELECT id, user_id, chat_id, label, color, created_at FROM chat_labels WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetChatLabels(ctx context.Context, userID uuid.UUID) ([]ChatLabel, error) {
	rows, err := q.db.QueryContext(ctx, getChatLabels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatLabel
	for rows.Next() {
		var i ChatLabel
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChatID,
			&i.Label,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPayment = `-- name: GetPayment :one
SELECT id, bot_id, user_id, amount, currency, status, stripe_id, description, metadata, created_at, updated_at FROM payments
WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.StripeID,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByStripeID = `-- name: GetPaymentByStripeID :one
SELECT id, bot_id, user_id, amount, currency, status, stripe_id, description, metadata, created_at, updated_at FROM payments
WHERE stripe_id = $1
`

func (q *Queries) GetPaymentByStripeID(ctx context.Context, stripeID string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByStripeID, stripeID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.StripeID,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPremiumSettings = `-- name: GetPremiumSettings :one
SELECT user_id, hide_phone, away_message, away_message_enabled, updated_at FROM premium_settings WHERE user_id = $1
`

func (q *Queries) GetPremiumSettings(ctx context.Context, userID uuid.UUID) (PremiumSetting, error) {
	row := q.db.QueryRowContext(ctx, getPremiumSettings, userID)
	var i PremiumSetting
	err := row.Scan(
		&i.UserID,
		&i.HidePhone,
		&i.AwayMessage,
		&i.AwayMessageEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByUserID = `-- name: GetSubscriptionByUserID :one
SELECT id, user_id, plan, status, started_at, expires_at, auto_renew, payment_ref, metadata, stripe_customer_id, stripe_sub_id, current_period_end, cancel_at_period_end, updated_at FROM subscriptions WHERE user_id = $1
`

func (q *Queries) GetSubscriptionByUserID(ctx context.Context, userID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByUserID, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.AutoRenew,
		&i.PaymentRef,
		&i.Metadata,
		&i.StripeCustomerID,
		&i.StripeSubID,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPayments = `-- name: GetUserPayments :many
SELECT id, bot_id, user_id, amount, currency, status, stripe_id, description, metadata, created_at, updated_at FROM payments
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserPaymentsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetUserPayments(ctx context.Context, arg GetUserPaymentsParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, getUserPayments, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.UserID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.StripeID,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdatePaymentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentStatus, arg.ID, arg.Status)
	return err
}

const updateSubscriptionByStripeID = `-- name: UpdateSubscriptionByStripeID :exec
UPDATE subscriptions SET
    status               = $2,
    current_period_end   = $3,
    cancel_at_period_end = $4,
    updated_at           = now()
WHERE stripe_sub_id = $1
`

type UpdateSubscriptionByStripeIDParams struct {
	StripeSubID       string       `json:"stripe_sub_id"`
	Status            string       `json:"status"`
	CurrentPeriodEnd  sql.NullTime `json:"current_period_end"`
	CancelAtPeriodEnd bool         `json:"cancel_at_period_end"`
}

func (q *Queries) UpdateSubscriptionByStripeID(ctx context.Context, arg UpdateSubscriptionByStripeIDParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionByStripeID,
		arg.StripeSubID,
		arg.Status,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
	)
	return err
}

const updateSubscriptionCancelAtPeriodEnd = `-- name: UpdateSubscriptionCancelAtPeriodEnd :exec
UPDATE subscriptions SET
    cancel_at_period_end = $2,
    updated_at           = now()
WHERE user_id = $1
`

type UpdateSubscriptionCancelAtPeriodEndParams struct {
	UserID            uuid.UUID `json:"user_id"`
	CancelAtPeriodEnd bool      `json:"cancel_at_period_end"`
}

func (q *Queries) UpdateSubscriptionCancelAtPeriodEnd(ctx context.Context, arg UpdateSubscriptionCancelAtPeriodEndParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionCancelAtPeriodEnd, arg.UserID, arg.CancelAtPeriodEnd)
	return err
}

const upsertBusinessProfile = `-- name: UpsertBusinessProfile :one
INSERT INTO business_profiles (user_id, business_name, category, description, address, email, website, phone_public, working_hours)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id) DO UPDATE SET
    business_name = EXCLUDED.business_name,
    category      = EXCLUDED.category,
    description   = EXCLUDED.description,
    address       = EXCLUDED.address,
    email         = EXCLUDED.email,
    website       = EXCLUDED.website,
    phone_public  = EXCLUDED.phone_public,
    working_hours = EXCLUDED.working_hours,
    updated_at    = NOW()
RETURNING user_id, business_name, category, description, address, email, website, phone_public, working_hours, is_verified, created_at, updated_at
`

type UpsertBusinessProfileParams struct {
	UserID       uuid.UUID       `json:"user_id"`
	BusinessName string          `json:"business_name"`
	Category     string          `json:"category"`
	Description  string          `json:"description"`
	Address      string          `json:"address"`
	Email        string          `json:"email"`
	Website      string          `json:"website"`
	PhonePublic  string          `json:"phone_public"`
	WorkingHours json.RawMessage `json:"working_hours"`
}

func (q *Queries) UpsertBusinessProfile(ctx context.Context, arg UpsertBusinessProfileParams) (BusinessProfile, error) {
	row := q.db.QueryRowContext(ctx, upsertBusinessProfile,
		arg.UserID,
		arg.BusinessName,
		arg.Category,
		arg.Description,
		arg.Address,
		arg.Email,
		arg.Website,
		arg.PhonePublic,
		arg.WorkingHours,
	)
	var i BusinessProfile
	err := row.Scan(
		&i.UserID,
		&i.BusinessName,
		&i.Category,
		&i.Description,
		&i.Address,
		&i.Email,
		&i.Website,
		&i.PhonePublic,
		&i.WorkingHours,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPremiumSettings = `-- name: UpsertPremiumSettings :exec
INSERT INTO premium_settings (user_id, hide_phone, away_message, away_message_enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    hide_phone           = EXCLUDED.hide_phone,
    away_message         = EXCLUDED.away_message,
    away_message_enabled = EXCLUDED.away_message_enabled,
    updated_at           = now()
`

type UpsertPremiumSettingsParams struct {
	UserID             uuid.UUID `json:"user_id"`
	HidePhone          bool      `json:"hide_phone"`
	AwayMessage        string    `json:"away_message"`
	AwayMessageEnabled bool      `json:"away_message_enabled"`
}

func (q *Queries) UpsertPremiumSettings(ctx context.Context, arg UpsertPremiumSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertPremiumSettings,
		arg.UserID,
		arg.HidePhone,
		arg.AwayMessage,
		arg.AwayMessageEnabled,
	)
	return err
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO subscriptions (user_id, stripe_customer_id, stripe_sub_id, plan, status)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET
    stripe_customer_id   = EXCLUDED.stripe_customer_id,
    stripe_sub_id        = EXCLUDED.stripe_sub_id,
    plan                 = EXCLUDED.plan,
    status               = EXCLUDED.status,
    updated_at           = now()
`

type UpsertSubscriptionParams struct {
	UserID           uuid.UUID `json:"user_id"`
	StripeCustomerID string    `json:"stripe_customer_id"`
	StripeSubID      string    `json:"stripe_sub_id"`
	Plan             string    `json:"plan"`
	Status           string    `json:"status"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSubscription,
		arg.UserID,
		arg.StripeCustomerID,
		arg.StripeSubID,
		arg.Plan,
		arg.Status,
	)
	return err
}
