// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AddChatMember(ctx context.Context, arg AddChatMemberParams) error
	CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateMessageStatus(ctx context.Context, arg CreateMessageStatusParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateDevice(ctx context.Context, id uuid.UUID) error
	DeleteAllUserSessions(ctx context.Context, userID uuid.UUID) error
	DeleteDevice(ctx context.Context, id uuid.UUID) error
	DeleteMessageForAll(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, refreshToken string) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	EditMessage(ctx context.Context, arg EditMessageParams) (Message, error)
	GetChatByID(ctx context.Context, id uuid.UUID) (Chat, error)
	GetChatMembers(ctx context.Context, chatID uuid.UUID) ([]ChatMember, error)
	GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]Message, error)
	GetDeviceByID(ctx context.Context, id uuid.UUID) (Device, error)
	GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error)
	GetPinnedMessages(ctx context.Context, chatID uuid.UUID) ([]Message, error)
	GetSessionByToken(ctx context.Context, refreshToken string) (Session, error)
	GetUserByEmail(ctx context.Context, email sql.NullString) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone sql.NullString) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserChats(ctx context.Context, userID uuid.UUID) ([]Chat, error)
	GetUserDevices(ctx context.Context, userID uuid.UUID) (Device, error)
	PinMessage(ctx context.Context, id uuid.UUID) error
	RemoveChatMember(ctx context.Context, arg RemoveChatMemberParams) error
	UpdateChatMemberRole(ctx context.Context, arg UpdateChatMemberRoleParams) error
	UpdateDevicePushToken(ctx context.Context, arg UpdateDevicePushTokenParams) error
	UpdateMessageDelivered(ctx context.Context, arg UpdateMessageDeliveredParams) error
	UpdateMessageRead(ctx context.Context, arg UpdateMessageReadParams) error
	UpdateUserOnlineStatus(ctx context.Context, arg UpdateUserOnlineStatusParams) error
}

var _ Querier = (*Queries)(nil)
