// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const banUser = `-- name: BanUser :one
INSERT INTO user_bans (
    user_id,
    banned_by,
    reason,
    permanent,
    expires_at
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, banned_by, reason, permanent, expires_at, created_at
`

type BanUserParams struct {
	UserID    uuid.UUID     `json:"user_id"`
	BannedBy  uuid.NullUUID `json:"banned_by"`
	Reason    string        `json:"reason"`
	Permanent sql.NullBool  `json:"permanent"`
	ExpiresAt sql.NullTime  `json:"expires_at"`
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) (UserBan, error) {
	row := q.db.QueryRowContext(ctx, banUser,
		arg.UserID,
		arg.BannedBy,
		arg.Reason,
		arg.Permanent,
		arg.ExpiresAt,
	)
	var i UserBan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BannedBy,
		&i.Reason,
		&i.Permanent,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    reporter_id,
    reported_user_id,
    reported_message_id,
    reason,
    description
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, reporter_id, reported_user_id, reported_message_id, reason, description, status, reviewed_by, reviewed_at, created_at
`

type CreateReportParams struct {
	ReporterID        uuid.UUID      `json:"reporter_id"`
	ReportedUserID    uuid.UUID      `json:"reported_user_id"`
	ReportedMessageID sql.NullInt64  `json:"reported_message_id"`
	Reason            string         `json:"reason"`
	Description       sql.NullString `json:"description"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, createReport,
		arg.ReporterID,
		arg.ReportedUserID,
		arg.ReportedMessageID,
		arg.Reason,
		arg.Description,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ReportedUserID,
		&i.ReportedMessageID,
		&i.Reason,
		&i.Description,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingReports = `-- name: GetPendingReports :many
SELECT id, reporter_id, reported_user_id, reported_message_id, reason, description, status, reviewed_by, reviewed_at, created_at FROM reports
WHERE status = 'pending'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetPendingReportsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetPendingReports(ctx context.Context, arg GetPendingReportsParams) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, getPendingReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ReportedUserID,
			&i.ReportedMessageID,
			&i.Reason,
			&i.Description,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserReportsCount = `-- name: GetUserReportsCount :one
SELECT COUNT(*)::bigint FROM reports
WHERE reported_user_id = $1
AND status = 'actioned'
`

func (q *Queries) GetUserReportsCount(ctx context.Context, reportedUserID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserReportsCount, reportedUserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const isUserBanned = `-- name: IsUserBanned :one
SELECT CAST(is_user_banned($1::uuid) AS boolean) AS banned
`

func (q *Queries) IsUserBanned(ctx context.Context, dollar_1 uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserBanned, dollar_1)
	var banned bool
	err := row.Scan(&banned)
	return banned, err
}

const updateReportStatus = `-- name: UpdateReportStatus :exec
UPDATE reports
SET status = $1,
    reviewed_by = $2,
    reviewed_at = NOW()
WHERE id = $3
`

type UpdateReportStatusParams struct {
	Status     sql.NullString `json:"status"`
	ReviewedBy uuid.NullUUID  `json:"reviewed_by"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateReportStatus, arg.Status, arg.ReviewedBy, arg.ID)
	return err
}
