// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions(user_id,device_id,refresh_token,ip_address,expires_at)
VALUES ($1,$2,$3,$4,$5) RETURNING id, user_id, device_id, refresh_token, ip_address, expires_at, created_at, user_agent, fingerprint, revoked_at
`

type CreateSessionParams struct {
	UserID       uuid.UUID     `json:"user_id"`
	DeviceID     uuid.NullUUID `json:"device_id"`
	RefreshToken string        `json:"refresh_token"`
	IpAddress    pqtype.Inet   `json:"ip_address"`
	ExpiresAt    time.Time     `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.UserID,
		arg.DeviceID,
		arg.RefreshToken,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.RefreshToken,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.Fingerprint,
		&i.RevokedAt,
	)
	return i, err
}

const deleteAllUserSessions = `-- name: DeleteAllUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllUserSessions, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE refresh_token =$1
`

func (q *Queries) DeleteSession(ctx context.Context, refreshToken string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, refreshToken)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, device_id, refresh_token, ip_address, expires_at, created_at, user_agent, fingerprint, revoked_atFROM sessions WHERE refresh_token=$1 AND expires_at>NOW()
`

func (q *Queries) GetSessionByToken(ctx context.Context, refreshToken string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, refreshToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.RefreshToken,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.Fingerprint,
		&i.RevokedAt,
	)
	return i, err
}
