// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stickers.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addStickerToPack = `-- name: AddStickerToPack :one
INSERT INTO stickers (pack_id, media_id, emoji, position, format, lottie_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, pack_id, emoji, url, created_at, media_id, position, format, lottie_url
`

type AddStickerToPackParams struct {
	PackID    uuid.UUID      `json:"pack_id"`
	MediaID   uuid.NullUUID  `json:"media_id"`
	Emoji     sql.NullString `json:"emoji"`
	Position  sql.NullInt32  `json:"position"`
	Format    sql.NullString `json:"format"`
	LottieUrl sql.NullString `json:"lottie_url"`
}

func (q *Queries) AddStickerToPack(ctx context.Context, arg AddStickerToPackParams) (Sticker, error) {
	row := q.db.QueryRowContext(ctx, addStickerToPack,
		arg.PackID,
		arg.MediaID,
		arg.Emoji,
		arg.Position,
		arg.Format,
		arg.LottieUrl,
	)
	var i Sticker
	err := row.Scan(
		&i.ID,
		&i.PackID,
		&i.Emoji,
		&i.Url,
		&i.CreatedAt,
		&i.MediaID,
		&i.Position,
		&i.Format,
		&i.LottieUrl,
	)
	return i, err
}

const createStickerPack = `-- name: CreateStickerPack :one
INSERT INTO sticker_packs (name, author_id, thumb_url, is_official)
VALUES ($1, $2, $3, $4)
RETURNING id, name, author_id, is_official, created_at, thumb_url
`

type CreateStickerPackParams struct {
	Name       string         `json:"name"`
	AuthorID   uuid.NullUUID  `json:"author_id"`
	ThumbUrl   sql.NullString `json:"thumb_url"`
	IsOfficial sql.NullBool   `json:"is_official"`
}

func (q *Queries) CreateStickerPack(ctx context.Context, arg CreateStickerPackParams) (StickerPack, error) {
	row := q.db.QueryRowContext(ctx, createStickerPack,
		arg.Name,
		arg.AuthorID,
		arg.ThumbUrl,
		arg.IsOfficial,
	)
	var i StickerPack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AuthorID,
		&i.IsOfficial,
		&i.CreatedAt,
		&i.ThumbUrl,
	)
	return i, err
}

const getPackStickers = `-- name: GetPackStickers :many
SELECT
    s.id,
    s.emoji,
    s.position,
    s.format,
    s.lottie_url,
    m.object_key,
    m.mime_type,
    m.width,
    m.height
FROM stickers s
JOIN media m ON m.id = s.media_id
WHERE s.pack_id = $1
ORDER BY s.position ASC
`

type GetPackStickersRow struct {
	ID        uuid.UUID      `json:"id"`
	Emoji     sql.NullString `json:"emoji"`
	Position  sql.NullInt32  `json:"position"`
	Format    sql.NullString `json:"format"`
	LottieUrl sql.NullString `json:"lottie_url"`
	ObjectKey string         `json:"object_key"`
	MimeType  string         `json:"mime_type"`
	Width     sql.NullInt32  `json:"width"`
	Height    sql.NullInt32  `json:"height"`
}

func (q *Queries) GetPackStickers(ctx context.Context, packID uuid.UUID) ([]GetPackStickersRow, error) {
	rows, err := q.db.QueryContext(ctx, getPackStickers, packID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPackStickersRow
	for rows.Next() {
		var i GetPackStickersRow
		if err := rows.Scan(
			&i.ID,
			&i.Emoji,
			&i.Position,
			&i.Format,
			&i.LottieUrl,
			&i.ObjectKey,
			&i.MimeType,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicStickerPacks = `-- name: GetPublicStickerPacks :many
SELECT
    sp.id,
    sp.name,
    sp.thumb_url,
    sp.is_official,
    sp.created_at
FROM sticker_packs sp
ORDER BY sp.is_official DESC, sp.created_at DESC
`

type GetPublicStickerPacksRow struct {
	ID         uuid.UUID      `json:"id"`
	Name       string         `json:"name"`
	ThumbUrl   sql.NullString `json:"thumb_url"`
	IsOfficial sql.NullBool   `json:"is_official"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetPublicStickerPacks(ctx context.Context) ([]GetPublicStickerPacksRow, error) {
	rows, err := q.db.QueryContext(ctx, getPublicStickerPacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublicStickerPacksRow
	for rows.Next() {
		var i GetPublicStickerPacksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ThumbUrl,
			&i.IsOfficial,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStickersByEmoji = `-- name: GetStickersByEmoji :many
SELECT
    s.id,
    s.emoji,
    s.format,
    s.lottie_url,
    sp.name  AS pack_name,
    sp.id    AS pack_id,
    m.object_key,
    m.mime_type,
    m.width,
    m.height,
    -- installed = 1 если пак установлен у пользователя, иначе 0
    CASE WHEN usp.user_id IS NOT NULL THEN 1 ELSE 0 END AS is_installed
FROM stickers s
JOIN sticker_packs sp ON sp.id = s.pack_id
JOIN media m ON m.id = s.media_id
LEFT JOIN user_sticker_packs usp
    ON usp.pack_id = sp.id AND usp.user_id = $1
WHERE s.emoji = $2
ORDER BY is_installed DESC, s.position ASC
LIMIT 24
`

type GetStickersByEmojiParams struct {
	UserID uuid.UUID      `json:"user_id"`
	Emoji  sql.NullString `json:"emoji"`
}

type GetStickersByEmojiRow struct {
	ID          uuid.UUID      `json:"id"`
	Emoji       sql.NullString `json:"emoji"`
	Format      sql.NullString `json:"format"`
	LottieUrl   sql.NullString `json:"lottie_url"`
	PackName    string         `json:"pack_name"`
	PackID      uuid.UUID      `json:"pack_id"`
	ObjectKey   string         `json:"object_key"`
	MimeType    string         `json:"mime_type"`
	Width       sql.NullInt32  `json:"width"`
	Height      sql.NullInt32  `json:"height"`
	IsInstalled int32          `json:"is_installed"`
}

// Используется для inline suggestions: клиент присылает точный эмодзи
// Сначала стикеры из установленных паков пользователя, потом остальные
func (q *Queries) GetStickersByEmoji(ctx context.Context, arg GetStickersByEmojiParams) ([]GetStickersByEmojiRow, error) {
	rows, err := q.db.QueryContext(ctx, getStickersByEmoji, arg.UserID, arg.Emoji)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStickersByEmojiRow
	for rows.Next() {
		var i GetStickersByEmojiRow
		if err := rows.Scan(
			&i.ID,
			&i.Emoji,
			&i.Format,
			&i.LottieUrl,
			&i.PackName,
			&i.PackID,
			&i.ObjectKey,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.IsInstalled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStickerPacks = `-- name: GetUserStickerPacks :many
SELECT
    sp.id,
    sp.name,
    sp.thumb_url,
    sp.is_official,
    usp.position,
    usp.added_at
FROM sticker_packs sp
JOIN user_sticker_packs usp ON usp.pack_id = sp.id
WHERE usp.user_id = $1
ORDER BY usp.added_at DESC
`

type GetUserStickerPacksRow struct {
	ID         uuid.UUID      `json:"id"`
	Name       string         `json:"name"`
	ThumbUrl   sql.NullString `json:"thumb_url"`
	IsOfficial sql.NullBool   `json:"is_official"`
	Position   sql.NullInt32  `json:"position"`
	AddedAt    sql.NullTime   `json:"added_at"`
}

func (q *Queries) GetUserStickerPacks(ctx context.Context, userID uuid.UUID) ([]GetUserStickerPacksRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserStickerPacks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserStickerPacksRow
	for rows.Next() {
		var i GetUserStickerPacksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ThumbUrl,
			&i.IsOfficial,
			&i.Position,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const installStickerPack = `-- name: InstallStickerPack :exec
INSERT INTO user_sticker_packs (user_id, pack_id, position)
VALUES (
    $1, $2,
    (SELECT COALESCE(MAX(position) + 1, 0) FROM user_sticker_packs WHERE user_id = $1)
)
ON CONFLICT (user_id, pack_id) DO NOTHING
`

type InstallStickerPackParams struct {
	UserID uuid.UUID `json:"user_id"`
	PackID uuid.UUID `json:"pack_id"`
}

func (q *Queries) InstallStickerPack(ctx context.Context, arg InstallStickerPackParams) error {
	_, err := q.db.ExecContext(ctx, installStickerPack, arg.UserID, arg.PackID)
	return err
}

const searchStickers = `-- name: SearchStickers :many
SELECT
    s.id,
    s.emoji,
    s.format,
    s.lottie_url,
    sp.name AS pack_name,
    m.object_key,
    m.mime_type,
    m.width,
    m.height
FROM stickers s
JOIN sticker_packs sp ON sp.id = s.pack_id
JOIN media m ON m.id = s.media_id
WHERE s.emoji ILIKE '%' || $1 || '%'
LIMIT 50
`

type SearchStickersRow struct {
	ID        uuid.UUID      `json:"id"`
	Emoji     sql.NullString `json:"emoji"`
	Format    sql.NullString `json:"format"`
	LottieUrl sql.NullString `json:"lottie_url"`
	PackName  string         `json:"pack_name"`
	ObjectKey string         `json:"object_key"`
	MimeType  string         `json:"mime_type"`
	Width     sql.NullInt32  `json:"width"`
	Height    sql.NullInt32  `json:"height"`
}

func (q *Queries) SearchStickers(ctx context.Context, query sql.NullString) ([]SearchStickersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchStickers, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchStickersRow
	for rows.Next() {
		var i SearchStickersRow
		if err := rows.Scan(
			&i.ID,
			&i.Emoji,
			&i.Format,
			&i.LottieUrl,
			&i.PackName,
			&i.ObjectKey,
			&i.MimeType,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uninstallStickerPack = `-- name: UninstallStickerPack :exec
DELETE FROM user_sticker_packs
WHERE user_id = $1 AND pack_id = $2
`

type UninstallStickerPackParams struct {
	UserID uuid.UUID `json:"user_id"`
	PackID uuid.UUID `json:"pack_id"`
}

func (q *Queries) UninstallStickerPack(ctx context.Context, arg UninstallStickerPackParams) error {
	_, err := q.db.ExecContext(ctx, uninstallStickerPack, arg.UserID, arg.PackID)
	return err
}
