// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stories.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const addCloseFriend = `-- name: AddCloseFriend :exec
INSERT INTO close_friends (user_id, friend_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddCloseFriendParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FriendID uuid.UUID `json:"friend_id"`
}

func (q *Queries) AddCloseFriend(ctx context.Context, arg AddCloseFriendParams) error {
	_, err := q.db.ExecContext(ctx, addCloseFriend, arg.UserID, arg.FriendID)
	return err
}

const archiveStory = `-- name: ArchiveStory :exec
UPDATE stories SET is_archived = TRUE WHERE id = $1 AND user_id = $2
`

type ArchiveStoryParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ArchiveStory(ctx context.Context, arg ArchiveStoryParams) error {
	_, err := q.db.ExecContext(ctx, archiveStory, arg.ID, arg.UserID)
	return err
}

const cleanupExpiredStories = `-- name: CleanupExpiredStories :exec
UPDATE stories
SET is_archived = TRUE
WHERE expires_at < NOW() AND is_archived = FALSE
`

func (q *Queries) CleanupExpiredStories(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredStories)
	return err
}

const createStory = `-- name: CreateStory :one
INSERT INTO stories (user_id, media_url, thumbnail_url, type, caption, audience, media_id, sticker_data, music_data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, media_url, thumbnail_url, type, caption, views_count, expires_at, created_at, metadata, is_archived, audience, media_id, sticker_data, music_data
`

type CreateStoryParams struct {
	UserID       uuid.UUID             `json:"user_id"`
	MediaUrl     string                `json:"media_url"`
	ThumbnailUrl sql.NullString        `json:"thumbnail_url"`
	Type         sql.NullString        `json:"type"`
	Caption      sql.NullString        `json:"caption"`
	Audience     sql.NullString        `json:"audience"`
	MediaID      uuid.NullUUID         `json:"media_id"`
	StickerData  pqtype.NullRawMessage `json:"sticker_data"`
	MusicData    pqtype.NullRawMessage `json:"music_data"`
}

func (q *Queries) CreateStory(ctx context.Context, arg CreateStoryParams) (Story, error) {
	row := q.db.QueryRowContext(ctx, createStory,
		arg.UserID,
		arg.MediaUrl,
		arg.ThumbnailUrl,
		arg.Type,
		arg.Caption,
		arg.Audience,
		arg.MediaID,
		arg.StickerData,
		arg.MusicData,
	)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MediaUrl,
		&i.ThumbnailUrl,
		&i.Type,
		&i.Caption,
		&i.ViewsCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Metadata,
		&i.IsArchived,
		&i.Audience,
		&i.MediaID,
		&i.StickerData,
		&i.MusicData,
	)
	return i, err
}

const deleteStory = `-- name: DeleteStory :exec
DELETE FROM stories WHERE id = $1 AND user_id = $2
`

type DeleteStoryParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteStory(ctx context.Context, arg DeleteStoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteStory, arg.ID, arg.UserID)
	return err
}

const getActiveStories = `-- name: GetActiveStories :many
SELECT s.id, s.user_id, s.media_url, s.thumbnail_url, s.type, s.caption, s.views_count, s.expires_at, s.created_at, s.metadata, s.is_archived, s.audience, s.media_id, s.sticker_data, s.music_data, u.username, u.avatar_url
FROM stories s
JOIN users u ON u.id = s.user_id
WHERE s.expires_at > NOW()
AND s.is_archived = FALSE
AND s.user_id = $1
ORDER BY s.created_at DESC
`

type GetActiveStoriesRow struct {
	ID           uuid.UUID             `json:"id"`
	UserID       uuid.UUID             `json:"user_id"`
	MediaUrl     string                `json:"media_url"`
	ThumbnailUrl sql.NullString        `json:"thumbnail_url"`
	Type         sql.NullString        `json:"type"`
	Caption      sql.NullString        `json:"caption"`
	ViewsCount   sql.NullInt32         `json:"views_count"`
	ExpiresAt    sql.NullTime          `json:"expires_at"`
	CreatedAt    sql.NullTime          `json:"created_at"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	IsArchived   sql.NullBool          `json:"is_archived"`
	Audience     sql.NullString        `json:"audience"`
	MediaID      uuid.NullUUID         `json:"media_id"`
	StickerData  pqtype.NullRawMessage `json:"sticker_data"`
	MusicData    pqtype.NullRawMessage `json:"music_data"`
	Username     string                `json:"username"`
	AvatarUrl    sql.NullString        `json:"avatar_url"`
}

func (q *Queries) GetActiveStories(ctx context.Context, userID uuid.UUID) ([]GetActiveStoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveStories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveStoriesRow
	for rows.Next() {
		var i GetActiveStoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaUrl,
			&i.ThumbnailUrl,
			&i.Type,
			&i.Caption,
			&i.ViewsCount,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Metadata,
			&i.IsArchived,
			&i.Audience,
			&i.MediaID,
			&i.StickerData,
			&i.MusicData,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivedStories = `-- name: GetArchivedStories :many
SELECT id, user_id, media_url, thumbnail_url, type, caption, views_count, expires_at, created_at, metadata, is_archived, audience, media_id, sticker_data, music_data FROM stories
WHERE user_id = $1 AND is_archived = TRUE
ORDER BY created_at DESC
`

func (q *Queries) GetArchivedStories(ctx context.Context, userID uuid.UUID) ([]Story, error) {
	rows, err := q.db.QueryContext(ctx, getArchivedStories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Story
	for rows.Next() {
		var i Story
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaUrl,
			&i.ThumbnailUrl,
			&i.Type,
			&i.Caption,
			&i.ViewsCount,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Metadata,
			&i.IsArchived,
			&i.Audience,
			&i.MediaID,
			&i.StickerData,
			&i.MusicData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCloseFriends = `-- name: GetCloseFriends :many
SELECT u.id, u.username, u.avatar_url
FROM close_friends cf
JOIN users u ON u.id = cf.friend_id
WHERE cf.user_id = $1
ORDER BY cf.created_at DESC
`

type GetCloseFriendsRow struct {
	ID        uuid.UUID      `json:"id"`
	Username  string         `json:"username"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) GetCloseFriends(ctx context.Context, userID uuid.UUID) ([]GetCloseFriendsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCloseFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCloseFriendsRow
	for rows.Next() {
		var i GetCloseFriendsRow
		if err := rows.Scan(&i.ID, &i.Username, &i.AvatarUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoriesFeed = `-- name: GetStoriesFeed :many
SELECT s.id, s.user_id, s.media_url, s.thumbnail_url, s.type, s.caption, s.views_count, s.expires_at, s.created_at, s.metadata, s.is_archived, s.audience, s.media_id, s.sticker_data, s.music_data, u.username, u.avatar_url
FROM stories s
JOIN users u ON u.id = s.user_id
WHERE s.expires_at > NOW()
AND s.is_archived = FALSE
AND (
    s.audience = 'everyone'
    OR (s.audience = 'close_friends' AND EXISTS (
        SELECT 1 FROM close_friends cf
        WHERE cf.user_id = s.user_id AND cf.friend_id = $1
    ))
)
ORDER BY s.created_at DESC
LIMIT 100
`

type GetStoriesFeedRow struct {
	ID           uuid.UUID             `json:"id"`
	UserID       uuid.UUID             `json:"user_id"`
	MediaUrl     string                `json:"media_url"`
	ThumbnailUrl sql.NullString        `json:"thumbnail_url"`
	Type         sql.NullString        `json:"type"`
	Caption      sql.NullString        `json:"caption"`
	ViewsCount   sql.NullInt32         `json:"views_count"`
	ExpiresAt    sql.NullTime          `json:"expires_at"`
	CreatedAt    sql.NullTime          `json:"created_at"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	IsArchived   sql.NullBool          `json:"is_archived"`
	Audience     sql.NullString        `json:"audience"`
	MediaID      uuid.NullUUID         `json:"media_id"`
	StickerData  pqtype.NullRawMessage `json:"sticker_data"`
	MusicData    pqtype.NullRawMessage `json:"music_data"`
	Username     string                `json:"username"`
	AvatarUrl    sql.NullString        `json:"avatar_url"`
}

func (q *Queries) GetStoriesFeed(ctx context.Context, viewerID uuid.UUID) ([]GetStoriesFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, getStoriesFeed, viewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStoriesFeedRow
	for rows.Next() {
		var i GetStoriesFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaUrl,
			&i.ThumbnailUrl,
			&i.Type,
			&i.Caption,
			&i.ViewsCount,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Metadata,
			&i.IsArchived,
			&i.Audience,
			&i.MediaID,
			&i.StickerData,
			&i.MusicData,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoryReactions = `-- name: GetStoryReactions :many
SELECT sr.emoji, COUNT(*) as count
FROM story_reactions sr
WHERE sr.story_id = $1
GROUP BY sr.emoji
ORDER BY count DESC
`

type GetStoryReactionsRow struct {
	Emoji string `json:"emoji"`
	Count int64  `json:"count"`
}

func (q *Queries) GetStoryReactions(ctx context.Context, storyID uuid.UUID) ([]GetStoryReactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getStoryReactions, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStoryReactionsRow
	for rows.Next() {
		var i GetStoryReactionsRow
		if err := rows.Scan(&i.Emoji, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoryViewers = `-- name: GetStoryViewers :many
SELECT u.id, u.username, u.avatar_url, sv.viewed_at
FROM story_views sv
JOIN users u ON u.id = sv.user_id
WHERE sv.story_id = $1
ORDER BY sv.viewed_at DESC
`

type GetStoryViewersRow struct {
	ID        uuid.UUID      `json:"id"`
	Username  string         `json:"username"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	ViewedAt  sql.NullTime   `json:"viewed_at"`
}

func (q *Queries) GetStoryViewers(ctx context.Context, storyID uuid.UUID) ([]GetStoryViewersRow, error) {
	rows, err := q.db.QueryContext(ctx, getStoryViewers, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStoryViewersRow
	for rows.Next() {
		var i GetStoryViewersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarUrl,
			&i.ViewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementStoryViews = `-- name: IncrementStoryViews :exec
UPDATE stories SET views_count = views_count + 1 WHERE id = $1
`

func (q *Queries) IncrementStoryViews(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementStoryViews, id)
	return err
}

const reactToStory = `-- name: ReactToStory :exec
INSERT INTO story_reactions (story_id, user_id, emoji)
VALUES ($1, $2, $3)
ON CONFLICT (story_id, user_id) DO UPDATE SET emoji = $3
`

type ReactToStoryParams struct {
	StoryID uuid.UUID `json:"story_id"`
	UserID  uuid.UUID `json:"user_id"`
	Emoji   string    `json:"emoji"`
}

func (q *Queries) ReactToStory(ctx context.Context, arg ReactToStoryParams) error {
	_, err := q.db.ExecContext(ctx, reactToStory, arg.StoryID, arg.UserID, arg.Emoji)
	return err
}

const removeCloseFriend = `-- name: RemoveCloseFriend :exec
DELETE FROM close_friends WHERE user_id = $1 AND friend_id = $2
`

type RemoveCloseFriendParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FriendID uuid.UUID `json:"friend_id"`
}

func (q *Queries) RemoveCloseFriend(ctx context.Context, arg RemoveCloseFriendParams) error {
	_, err := q.db.ExecContext(ctx, removeCloseFriend, arg.UserID, arg.FriendID)
	return err
}

const viewStory = `-- name: ViewStory :exec
INSERT INTO story_views (story_id, user_id)
VALUES ($1, $2)
ON CONFLICT (story_id, user_id) DO NOTHING
`

type ViewStoryParams struct {
	StoryID uuid.UUID `json:"story_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) ViewStory(ctx context.Context, arg ViewStoryParams) error {
	_, err := q.db.ExecContext(ctx, viewStory, arg.StoryID, arg.UserID)
	return err
}
