// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(username,phone,email,password,language)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, username, phone, email, password, avatar_url, bio, is_online, last_seen, is_verified, is_bot, is_deleted, delete_at, language, created_at, updated_at, metadata
`

type CreateUserParams struct {
	Username string         `json:"username"`
	Phone    sql.NullString `json:"phone"`
	Email    sql.NullString `json:"email"`
	Password string         `json:"password"`
	Language sql.NullString `json:"language"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Phone,
		arg.Email,
		arg.Password,
		arg.Language,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Email,
		&i.Password,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsOnline,
		&i.LastSeen,
		&i.IsVerified,
		&i.IsBot,
		&i.IsDeleted,
		&i.DeleteAt,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users SET is_deleted = TRUE,delete_at =NOW()WHERE id =$1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, phone, email, password, avatar_url, bio, is_online, last_seen, is_verified, is_bot, is_deleted, delete_at, language, created_at, updated_at, metadata FROM users WHERE email =$1 AND is_deleted=FALSE
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Email,
		&i.Password,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsOnline,
		&i.LastSeen,
		&i.IsVerified,
		&i.IsBot,
		&i.IsDeleted,
		&i.DeleteAt,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, phone, email, password, avatar_url, bio, is_online, last_seen, is_verified, is_bot, is_deleted, delete_at, language, created_at, updated_at, metadata FROM users WHERE id = $1 AND is_deleted = FALSE
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Email,
		&i.Password,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsOnline,
		&i.LastSeen,
		&i.IsVerified,
		&i.IsBot,
		&i.IsDeleted,
		&i.DeleteAt,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, username, phone, email, password, avatar_url, bio, is_online, last_seen, is_verified, is_bot, is_deleted, delete_at, language, created_at, updated_at, metadata FROM users WHERE phone =$1 AND is_deleted=FALSE
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Email,
		&i.Password,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsOnline,
		&i.LastSeen,
		&i.IsVerified,
		&i.IsBot,
		&i.IsDeleted,
		&i.DeleteAt,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, phone, email, password, avatar_url, bio, is_online, last_seen, is_verified, is_bot, is_deleted, delete_at, language, created_at, updated_at, metadata FROM users WHERE username =$1 AND is_deleted=FALSE
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Email,
		&i.Password,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsOnline,
		&i.LastSeen,
		&i.IsVerified,
		&i.IsBot,
		&i.IsDeleted,
		&i.DeleteAt,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const updateUserOnlineStatus = `-- name: UpdateUserOnlineStatus :exec
UPDATE users SET is_online =$2, last_seen = NOW()WHERE id=$1
`

type UpdateUserOnlineStatusParams struct {
	ID       uuid.UUID    `json:"id"`
	IsOnline sql.NullBool `json:"is_online"`
}

func (q *Queries) UpdateUserOnlineStatus(ctx context.Context, arg UpdateUserOnlineStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserOnlineStatus, arg.ID, arg.IsOnline)
	return err
}
