// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voice_rooms.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const closeVoiceRoom = `-- name: CloseVoiceRoom :exec
UPDATE voice_rooms
SET is_active = FALSE
WHERE id = $1
`

func (q *Queries) CloseVoiceRoom(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, closeVoiceRoom, id)
	return err
}

const createVoiceRoom = `-- name: CreateVoiceRoom :one
INSERT INTO voice_rooms (id, chat_id, name, type, user_limit, is_active)
VALUES ($1, $2, $3, $4, $5, TRUE)
RETURNING id, chat_id, name, type, user_limit, is_active, created_at
`

type CreateVoiceRoomParams struct {
	ID        uuid.UUID      `json:"id"`
	ChatID    uuid.UUID      `json:"chat_id"`
	Name      string         `json:"name"`
	Type      sql.NullString `json:"type"`
	UserLimit sql.NullInt32  `json:"user_limit"`
}

func (q *Queries) CreateVoiceRoom(ctx context.Context, arg CreateVoiceRoomParams) (VoiceRoom, error) {
	row := q.db.QueryRowContext(ctx, createVoiceRoom,
		arg.ID,
		arg.ChatID,
		arg.Name,
		arg.Type,
		arg.UserLimit,
	)
	var i VoiceRoom
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Name,
		&i.Type,
		&i.UserLimit,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRoomParticipants = `-- name: DeleteRoomParticipants :exec
DELETE FROM voice_room_participants
WHERE room_id = $1
`

func (q *Queries) DeleteRoomParticipants(ctx context.Context, roomID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRoomParticipants, roomID)
	return err
}

const getActiveRoomsByChatID = `-- name: GetActiveRoomsByChatID :many
SELECT
    vr.id,
    vr.name,
    vr.type,
    vr.user_limit,
    vr.is_active,
    vr.created_at,
    COUNT(vrp.user_id)::int AS participant_count
FROM voice_rooms vr
LEFT JOIN voice_room_participants vrp ON vrp.room_id = vr.id
WHERE vr.chat_id = $1 AND vr.is_active = TRUE
GROUP BY vr.id, vr.name, vr.type, vr.user_limit, vr.is_active, vr.created_at
ORDER BY vr.created_at ASC
`

type GetActiveRoomsByChatIDRow struct {
	ID               uuid.UUID      `json:"id"`
	Name             string         `json:"name"`
	Type             sql.NullString `json:"type"`
	UserLimit        sql.NullInt32  `json:"user_limit"`
	IsActive         sql.NullBool   `json:"is_active"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	ParticipantCount int32          `json:"participant_count"`
}

func (q *Queries) GetActiveRoomsByChatID(ctx context.Context, chatID uuid.UUID) ([]GetActiveRoomsByChatIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveRoomsByChatID, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveRoomsByChatIDRow
	for rows.Next() {
		var i GetActiveRoomsByChatIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.UserLimit,
			&i.IsActive,
			&i.CreatedAt,
			&i.ParticipantCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomChatID = `-- name: GetRoomChatID :one
SELECT chat_id
FROM voice_rooms
WHERE id = $1
`

func (q *Queries) GetRoomChatID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getRoomChatID, id)
	var chat_id uuid.UUID
	err := row.Scan(&chat_id)
	return chat_id, err
}

const getRoomForJoin = `-- name: GetRoomForJoin :one
SELECT
    vr.user_limit,
    vr.chat_id,
    COUNT(vrp.user_id)::int AS participant_count
FROM voice_rooms vr
LEFT JOIN voice_room_participants vrp ON vrp.room_id = vr.id
WHERE vr.id = $1 AND vr.is_active = TRUE
GROUP BY vr.user_limit, vr.chat_id
`

type GetRoomForJoinRow struct {
	UserLimit        sql.NullInt32 `json:"user_limit"`
	ChatID           uuid.UUID     `json:"chat_id"`
	ParticipantCount int32         `json:"participant_count"`
}

func (q *Queries) GetRoomForJoin(ctx context.Context, id uuid.UUID) (GetRoomForJoinRow, error) {
	row := q.db.QueryRowContext(ctx, getRoomForJoin, id)
	var i GetRoomForJoinRow
	err := row.Scan(&i.UserLimit, &i.ChatID, &i.ParticipantCount)
	return i, err
}

const getRoomParticipants = `-- name: GetRoomParticipants :many
SELECT
    vrp.user_id,
    u.username,
    COALESCE(u.avatar_url, '') AS avatar_url,
    vrp.is_muted,
    vrp.is_deafened,
    vrp.is_video,
    vrp.is_speaking,
    vrp.joined_at
FROM voice_room_participants vrp
JOIN users u ON u.id = vrp.user_id
WHERE vrp.room_id = $1
ORDER BY vrp.joined_at ASC
`

type GetRoomParticipantsRow struct {
	UserID     uuid.UUID    `json:"user_id"`
	Username   string       `json:"username"`
	AvatarUrl  string       `json:"avatar_url"`
	IsMuted    sql.NullBool `json:"is_muted"`
	IsDeafened sql.NullBool `json:"is_deafened"`
	IsVideo    sql.NullBool `json:"is_video"`
	IsSpeaking sql.NullBool `json:"is_speaking"`
	JoinedAt   sql.NullTime `json:"joined_at"`
}

func (q *Queries) GetRoomParticipants(ctx context.Context, roomID uuid.UUID) ([]GetRoomParticipantsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoomParticipants, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomParticipantsRow
	for rows.Next() {
		var i GetRoomParticipantsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.AvatarUrl,
			&i.IsMuted,
			&i.IsDeafened,
			&i.IsVideo,
			&i.IsSpeaking,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinVoiceRoom = `-- name: JoinVoiceRoom :exec
INSERT INTO voice_room_participants (room_id, user_id)
VALUES ($1, $2)
ON CONFLICT (room_id, user_id) DO NOTHING
`

type JoinVoiceRoomParams struct {
	RoomID uuid.UUID `json:"room_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) JoinVoiceRoom(ctx context.Context, arg JoinVoiceRoomParams) error {
	_, err := q.db.ExecContext(ctx, joinVoiceRoom, arg.RoomID, arg.UserID)
	return err
}

const leaveVoiceRoom = `-- name: LeaveVoiceRoom :exec
DELETE FROM voice_room_participants
WHERE room_id = $1 AND user_id = $2
`

type LeaveVoiceRoomParams struct {
	RoomID uuid.UUID `json:"room_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) LeaveVoiceRoom(ctx context.Context, arg LeaveVoiceRoomParams) error {
	_, err := q.db.ExecContext(ctx, leaveVoiceRoom, arg.RoomID, arg.UserID)
	return err
}

const updateParticipantState = `-- name: UpdateParticipantState :exec
UPDATE voice_room_participants
SET
    is_muted    = COALESCE($3, is_muted),
    is_deafened = COALESCE($4, is_deafened),
    is_video    = COALESCE($5, is_video)
WHERE room_id = $1 AND user_id = $2
`

type UpdateParticipantStateParams struct {
	RoomID     uuid.UUID    `json:"room_id"`
	UserID     uuid.UUID    `json:"user_id"`
	IsMuted    sql.NullBool `json:"is_muted"`
	IsDeafened sql.NullBool `json:"is_deafened"`
	IsVideo    sql.NullBool `json:"is_video"`
}

func (q *Queries) UpdateParticipantState(ctx context.Context, arg UpdateParticipantStateParams) error {
	_, err := q.db.ExecContext(ctx, updateParticipantState,
		arg.RoomID,
		arg.UserID,
		arg.IsMuted,
		arg.IsDeafened,
		arg.IsVideo,
	)
	return err
}
