-- +goose Up
ALTER TABLE bots ADD COLUMN IF NOT EXISTS username       TEXT NOT NULL DEFAULT '';
ALTER TABLE bots ADD COLUMN IF NOT EXISTS name           TEXT NOT NULL DEFAULT '';
ALTER TABLE bots ADD COLUMN IF NOT EXISTS description    TEXT NOT NULL DEFAULT '';
ALTER TABLE bots ADD COLUMN IF NOT EXISTS avatar_url     TEXT NOT NULL DEFAULT '';
ALTER TABLE bots ADD COLUMN IF NOT EXISTS is_active      BOOL NOT NULL DEFAULT true;
ALTER TABLE bots ADD COLUMN IF NOT EXISTS is_ai_enabled  BOOL NOT NULL DEFAULT false;
ALTER TABLE bots ADD COLUMN IF NOT EXISTS webhook_url    TEXT NOT NULL DEFAULT '';
ALTER TABLE bots ADD COLUMN IF NOT EXISTS webhook_secret TEXT NOT NULL DEFAULT '';

CREATE UNIQUE INDEX IF NOT EXISTS idx_bots_username ON bots(username) WHERE username != '';
CREATE INDEX IF NOT EXISTS idx_bots_token ON bots(token);
CREATE INDEX IF NOT EXISTS idx_bots_owner ON bots(owner_id);

-- +goose Down
ALTER TABLE bots DROP COLUMN IF EXISTS username;
ALTER TABLE bots DROP COLUMN IF EXISTS name;
ALTER TABLE bots DROP COLUMN IF EXISTS description;
ALTER TABLE bots DROP COLUMN IF EXISTS avatar_url;
ALTER TABLE bots DROP COLUMN IF EXISTS is_active;
ALTER TABLE bots DROP COLUMN IF EXISTS is_ai_enabled;
ALTER TABLE bots DROP COLUMN IF EXISTS webhook_url;
ALTER TABLE bots DROP COLUMN IF EXISTS webhook_secret;